export const metadata = {
  title: "NOUR MAISON",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({ children }) {
  return children;
}
