import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import TopHeader from "../../components/shared/TopHeader/TopHeader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "NOUR MAISON",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico", // place favicon.ico in the public folder
  },
};

export default function RootLayout({ children }) {
  return (
    <>
      {children}
    </>
  );
}
