import BannerSwiper from "../../components/pages/Home/BannerSwiper/BannerSwiper";
import InstagramFeeds from "../../components/pages/Home/InstagramFeeds/InstagramFeeds";
import OurServices from "./../../components/pages/Home/OurServices/OurServices";
import BookTableSection from "./../../components/pages/Home/BookTableSection/BookTableSection";
import FeedBack from "../../components/pages/Home/FeedBack/FeedBack";
import ChefsSection from "./../../components/pages/Home/ChefsSection/ChefsSection";
import AboutUsSection from "../../components/pages/Home/AboutUsSection/AboutUsSection";
import FeaturesSections from "../../components/pages/Home/FeaturesSections/FeaturesSections";
import AfternoonTea from "./../../components/pages/Home/AfternoonTea/AfternoonTea";
import BlogSectionServer from "../../components/pages/Home/BlogsSection/BlogSectionServer";
import GoogleReviews from "../../components/pages/Home/GoogleReviews/GoogleReviews";
import HappyMoments from "../../components/pages/HappyMoments/HappyMoments";
import KidsSection from "../../components/pages/Home/KidsSection";
import NourKidsMenuHero from "../../components/pages/Home/KidsSection";
import VideoBanner from "../../components/pages/Home/MobileBanner";
import Annerversary from "../../components/pages/Home/Anneversary";
import RatingStars from "../../components/pages/Home/RatingWithSound";
import ChefsSection2 from "../../components/pages/Home/ChefsSection/ChefsSection2";
import HomaRoastMenu from "../../components/pages/Home/HomaRoastMenu";
export const metadata = {
  title: "Nour Maison | Halal French & middle eastern Café Restaurant",

  description:
    "Enjoy halal French and Middle Eastern brunch at Nour Maison in Milton Keynes. A cozy café offering pancakes, coffee, and elegant breakfast options.",
  keywords: [
    "Nour Maison",
    "Halal restaurant Milton Keynes",
    "Brasserie Milton Keynes",
    "Middle Eastern restaurant UK",
    "French cuisine Milton Keynes",
    "family-friendly dining Milton Keynes",
    "halal brunch Bletchley",
    "Mediterranean restaurant Milton Keynes",
    "artisan food UK",
    "halal dining Milton Keynes",
    "Elegant Restaurant",
    "Restaurant",
    "Café",
    "Fine Dining",
    "International Flavors",
    "Cozy Ambiance",
    "Unforgettable Moments",
    "Book your table today!",
    "Relaxing Atmosphere",
    "Modern Restaurant and Café",
    "Modern Restaurant and Café in Milton Keynes",
    "Modern Restaurant and Café in UK",
    "Best Café in Milton Keynes",
    "Best Café in UK",
    "Upscale Restaurant",
    "Upscale Café",
    "Upscale Restaurant and Café",
    "Upscale Restaurant and Café in Milton Keynes",
    "Upscale Restaurant and Café in UK",
    "Where to find elegant dining experience",
    "Where to find fine dining experience",
    "Where to find cozy ambiance",
    "Where to find unforgettable moments",
    "Where to find international flavors",
    "Nour Maison brunch",
    "best breakfast Milton Keynes",
    "lunch spots in Milton Keynes",
    "Milton Keynes coffee shop",
    "Milton Keynes French café",
    "where to eat in Milton Keynes",
    "cute cafés Milton Keynes",
    "best croissant in Milton Keynes",
    "coffee and pastry Milton Keynes",
    "elegant restaurant Milton Keynes",
    "romantic restaurants Milton Keynes",
    "cozy cafés near me MK",
    "best dessert shop Milton Keynes",
    "Milton Keynes afternoon tea",
    "café with outdoor seating MK",
    "breakfast places near me",
    "breakfast restaurants near me",
    "best breakfast near me",
    "breakfast cafe near me",
    "all day breakfast",
    "breakfast cafe",
    "places for breakfast near me",
    "milton keynes restaurants",
    "restaurants milton keynes",
    "the hub milton keynes",
    "breakfast cafes near me",
    "restaurants in milton keynes",
    "takeaway breakfast near me",
    "the hub mk",
    "best restaurants in milton keynes",
    "breakfasts near me",
    "afternoon tea milton keynes",
    "breakfast joints near me",
    "breakfast place near me",
    "bottomless brunch milton keynes",
    "breakfast milton keynes",
    "breakfast shops near me",
    "cafe near me breakfast",
    "milton keynes eating",
    "places to eat breakfast near me",
    "places to eat in milton keynes",
    "top restaurants in milton keynes",
    "b and b's in milton keynes",
    "breakfast mk",
    "fabrice brasserie",
    "places to eat in mk",
    "swan inn milton keynes",
    "b&b milton keynes",
    "bed and breakfast milton keynes",
    "best restaurants milton keynes",
    "best restaurants mk",
    "breakfast near me breakfast",
    "breakfast spots close to me",
    "cafe for breakfast",
    "cafe in mk",
    "coffee shops milton keynes",
    "eating in milton keynes",
    "healthy breakfast near me",
    "milton keynes food places",
    "mk hub",
    "places eat breakfast near me",
    "places to eat milton keynes",
    "restaurants in the hub milton keynes",
    "sunday breakfast near me",
    "where to go for breakfast near me",
    "where to have breakfast near me",
    "blossom room milton keynes",
    "brunch milton keynes",
    "buffet milton keynes",
    "fabrice",
    "milton keynes hub",
    "places to have breakfast near me",
    "restaurants in mk",
    "restaurants in the hub in milton keynes",
    "where can i get breakfast near me",
    "breakfast food near me",
    "coffee in milton keynes",
    "eating out in milton keynes",
    "fabrice milton keynes",
    "hub milton keynes",
    "hub mk",
    "milton keynes food",
    "milton keynes the hub",
    "open for breakfast now near me",
    "restaurant in mk",
    "bar milton keynes",
    "breakfast in milton keynes",
    "breakfast near me on sunday",
    "milton keynes turkish restaurant",
    "mk hub restaurants",
    "mk places to eat",
    "restaurants mk",
    "breakfast open near me",
    "breakfast restaurant near me",
    "brunch cafe near me",
    "milton keynes best restaurants",
    "milton keynes breakfast",
    "milton keynes hub restaurants",
    "restaurant milton keynes",
    "the hub restaurants mk",
    "turkish restaurant in milton keynes",
    "best places to eat in milton keynes",
    "breakfast around me",
    "breakfast near here",
    "cafe breakfast near me",
    "cafe for breakfast near me",
    "food milton keynes",
    "food near me breakfast",
    "good places to eat in milton keynes",
    "milton keynes city centre restaurants",
    "mk9 2fb",
    "all day breakfasts near me",
    "bed and breakfast in milton keynes",
    "breakfast and coffee near me",
    "breakfast cafeteria",
    "breakfast coffee near me",
    "breakfast meal near me",
    "breakfast places near me that are open",
    "breakfast shop near me",
    "brunch all day",
    "coffee shop milton keynes",
    "find a breakfast place near me",
    "find breakfast places near me",
    "food places in milton keynes",
    "lilly cafe - milton keynes",
    "milton keynes restaurant",
    "restaurants at the hub milton keynes",
    "sunday roast milton keynes",
    "where to eat breakfast near me",
    "afternoon tea in milton keynes",
    "best all day breakfast near me",
    "best breakfast cafe near me",
    "best breakfast in milton keynes",
    "best place for breakfast in milton keynes",
    "bottomless brunch mk",
    "breakfast close to here",
    "breakfast close to me now",
    "breakfast places near me open",
    "brunch and brew tenterden",
    "brunch in milton keynes",
    "cafes in milton keynes",
    "good breakfast oxford",
    "healthy brunch near me",
    "lilly cafe milton keynes",
    "lunch milton keynes",
    "milton keynes lunch",
    "milton keynes the hub restaurants",
    "posh restaurants in milton keynes",
    "restaurant in milton keynes",
    "restaurants in milton keynes hub",
    "turkish milton keynes",
    "best breakfast milton keynes",
    "best cooked breakfast near me",
    "best food in milton keynes",
    "best restaurants in mk",
    "breakfast diner near me",
    "breakfast food near me open",
    "breakfast in monton",
    "breakfast places open near me",
    "cafes for breakfast near me",
    "cafes near me for breakfast",
    "food in milton keynes",
    "furzton milton keynes",
    "milton keynes bottomless brunch",
    "milton keynes buffet restaurants",
    "milton keynes places to eat",
    "new restaurants milton keynes",
    "places open for breakfast near me",
    "posh restaurants milton keynes",
    "restaurants in central milton keynes",
    "restaurants near milton keynes",
    "steak house milton keynes",
    "sunday lunch milton keynes",
    "turkish food milton keynes",
    "where can i eat breakfast near me",
    "where eat breakfast near me",
    "where to eat for breakfast near me",
    "all day breakfast near me open now",
    "all day breakfasts",
    "all day.breakfast",
    "breakfast hemel hempstead",
    "breakfast reigate",
    "brunch near me within 0.2 mi",
    "coffee breakfast near me",
    "coffee shops milton",
    "furzton lake mk",
    "moments cafe and restaurant",
    "restaurants for breakfast near me",
    "restaurants in milton keynes centre",
    "restaurants in newport pagnell milton keynes",
    "take away breakfasts near me",
    "what time is breakfast",
    "where can i have breakfast near me",
    "where to eat in milton keynes",
    "best afternoon tea milton keynes",
    "best breakfast northampton",
    "best restaurant milton keynes",
    "best sunday lunch in milton keynes",
    "best sunday lunch milton keynes",
    "breakfast all day near me",
    "breakfast broughty ferry",
    "breakfast close to me",
    "breakfast in hemel",
    "breakfast in the city",
    "breakfast maidenhead",
    "breakfast near",
    "cafés near me breakfast",
    "food mk",
    "good restaurants in milton keynes",
    "happicup cafe milton keynes",
    "milton cafe",
    "mk restaurants",
    "open breakfast near me",
    "open breakfast places near me",
    "places to eat mk",
    "posh breakfast near me",
    "pub restaurants in milton keynes",
    "restaurant for breakfast near me",
    "restaurants in bletchley",
    "restaurants milton keynes centre",
    "restaurants milton keynes hub",
    "resturants in milton keynes",
    "roast dinner milton keynes",
    "all day breakfast milton keynes",
    "best breakfast in leamington spa",
    "best breakfast in northampton",
    "best brunch hertfordshire",
    "best cafe for breakfast near me",
    "best food milton keynes",
    "best places to eat milton keynes",
    "best restaurant in milton keynes",
    "best sunday roast in milton keynes",
    "best takeaway milton keynes",
    "bletchley restaurants",
    "blossoms milton keynes",
    "bottomless brunch in milton keynes",
    "breakfast at near me",
    "breakfast eggs near me",
    "breakfast enniskillen",
    "breakfast in billericay",
    "breakfast leighton buzzard",
    "breakfast pimlico",
    "breakfast places in milton keynes",
    "breakfast places in woburn",
    "breakfast waffles near me",
    "breakfast with eggs near me",
    "buffet in milton keynes",
    "cafe balti milton keynes",
    "cafes milton keynes",
    "caribbean milton keynes",
    "coffee milton keynes",
    "dinner in milton keynes",
    "enfield breakfast places",
    "food places milton keynes",
    "kikis cafe milton keynes",
    "marlborough breakfast places",
    "milton keynes afternoon tea",
    "milton keynes brunch",
    "milton keynes bubble tea",
    "mk cafe",
    "place to eat milton keynes",
    "restaurants at the hub",
    "restaurants near me breakfast",
    "restaurants near me for breakfast",
    "restaurants the hub",
    "restaurants the hub milton keynes",
    "afternoon tea near milton keynes",
    "all day breakfast mk",
    "american diner milton keynes",
    "b&b in milton keynes",
    "best bottomless brunch milton keynes",
    "best breakfast hertfordshire",
    "best breakfast hove",
    "best breakfast leamington spa",
    "best brunch milton keynes",
    "best places to eat in mk",
    "best sunday roast milton keynes",
    "breakfast by me",
    "breakfast cafe open near me",
    "breakfast ely",
    "breakfast epping",
    "breakfast faversham",
    "breakfast glenrothes",
    "breakfast hemel",
    "breakfast in amersham",
    "breakfast in berwick upon tweed",
    "breakfast in faversham",
    "breakfast in hove",
    "breakfast in leighton buzzard",
    "breakfast on sundays",
    "breakfast open now near me",
    "breakfast options near me",
    "breakfast places in epping",
    "breakfast places milton keynes",
    "breakfast places that are open",
    "breakfast saffron walden",
    "breakfast thame",
    "breakfast tiverton",
    "breakfast venues near me",
    "breakfast.near me",
    "brunch places milton keynes",
    "cafe breakfast menu",
    "caribbean food milton keynes",
    "christmas meal milton keynes",
    "christmas meals milton keynes",
    "fabrice mk",
    "greek food milton keynes",
    "hitchin breakfast",
    "hub mk restaurants",
    "m k cafe",
    "milton keynes bbq",
    "nearest breakfast cafe",
    "new restaurants in milton keynes",
    "places that do breakfast near me",
    "places to eat for breakfast near me",
    "restaurants in the hub",
    "take away milton keynes",
    "the best breakfast near me",
    "the hub milton keynes restaurants",
    "top restaurants milton keynes",
    "turkish restaurants milton keynes",
    "where can i find breakfast near me",
    "where can i get breakfast close to me",
    "where does breakfast near me",
    "where to find breakfast near me",
    "bedford breakfast",
    "best breakfast near me within 0.2 mi",
    "best brunch in milton keynes",
    "best roast dinner in milton keynes",
    "best victoria breakfast",
    "bottomless brunches in milton keynes",
    "breakfast amersham",
    "breakfast bletchley",
    "breakfast in bletchley",
    "breakfast in daventry",
    "breakfast in frome",
    "breakfast in melton mowbray",
    "breakfast in rickmansworth",
    "breakfast in thame",
    "breakfast in towcester",
    "breakfast in wantage",
    "breakfast locations near me",
    "breakfast lunch near me",
    "breakfast near me sunday",
    "breakfast nelson",
    "breakfast open",
    "breakfast places near by me",
    "breakfast places near me within 0.2 mi",
    "breakfast rickmansworth",
    "breakfast runcorn",
    "breakfast sunday",
    "breakfast towcester",
    "breakfast within 0.2 mi",
    "brunch near here",
    "cafe all day breakfast near me",
    "cafe max milton keynes",
    "caribbean restaurant milton keynes",
    "christmas day lunch milton keynes",
    "coffee brunch near me",
    "dining milton",
    "early morning breakfast near me",
    "fancy breakfast near me",
    "fancy restaurants milton keynes",
    "food brunch near me",
    "food court milton keynes",
    "food in mk",
    "food places in mk",
    "full english breakfast milton keynes",
    "kiki's cafe milton keynes",
    "lilly's cafe milton keynes",
    "milton keynes bed and breakfast",
    "milton keynes dinner",
    "milton keynes resturants",
    "mothers day milton keynes",
    "new restaurant milton keynes",
    "place for breakfast near me",
    "places open for breakfast",
    "places to eat in bletchley",
    "pub lunch milton keynes",
    "restaurant breakfast",
    "restaurants hub mk",
    "restaurants in milton keynes the hub",
    "restaurants in mk hub",
    "restaurants in the hub central milton keynes",
    "restaurants mk hub",
    "restaurants that serve breakfast near me",
    "rickmansworth breakfast",
    "sunday morning breakfast near me",
    "the hub restaurants milton keynes",
    "top rated restaurants milton keynes",
    "turkish restaurant mk",
    "turkish restaurants in milton keynes",
    "wallingford breakfast places",
    "where to eat milton keynes",
  ],
};

/**
 * Home component - Main page component of the application
 * Renders the complete homepage layout with various sections
 */
export default function Home() {
  return (
    <div className="overflow-hidden">
      {/* Header section containing video and banner elements */}
      <header className="">
        <div className=" md:hidden">
          <VideoBanner />
        </div>
        <div className="hidden md:block">
          <BannerSwiper />
        </div>
      </header>
      <main className="bg-s-700 overflow-hidden ">
        <section className="flex flex-col mb-[40px] mt-[20px] md:mb-[100px] relative z-20">
          <AboutUsSection />
          {/* <FeaturesSections /> */}
        </section>
        <HomaRoastMenu />
        {/* <GoogleReviews /> */}
        <InstagramFeeds />
        
        <BookTableSection />
        
        <NourKidsMenuHero
        title="Roasted to Perfection. Crafted to Impress"
        subTitle={"Discover our signature roast lineup — bold flavors, slow-cooked artistry."}
          cta={"Roast Menu"}
          ctaLink={"/roast-menu"}
        src="/images/nour reverse.mp4"
        poster="/images/download (7).jfif"
      />
        
         <AfternoonTea />
        {/* <EntryDesign /> */}
        {/* <OurServices /> */}
        {/* <HappyMoments withBg={true} /> */}
        <FeedBack />
        {/* <BlogSectionServer /> */}
        {/* <ChefsSection /> */}
        <ChefsSection2 />
        <Annerversary />
      </main>
    </div>
  );
}
