export const commonNourMaisonKeywords = [
  "Nour Maison",
  "Nour Maison Milton Keynes",
  "Nour Maison MK",
  "Nour Maison CMK",
  "Nour Maison menu",
  "Nour Maison brunch",
  "Nour Maison café",
  "Nour Maison afternoon tea",

  "café Milton Keynes",
  "best café Milton Keynes",
  "best cafe Milton Keynes",
  "coffee shop Milton Keynes",
  "best coffee shop Milton Keynes",
  "coffee and brunch Milton Keynes",
  "café near me Milton Keynes",
  "modern café Milton Keynes",
  "luxury café Milton Keynes",
  "family café Milton Keynes",
  "halal café Milton Keynes",
  "halal coffee shop Milton Keynes",

  "brunch Milton Keynes",
  "best brunch Milton Keynes",
  "brunch near me Milton Keynes",
  "brunch café Milton Keynes",
  "brunch menu Milton Keynes",
  "breakfast Milton Keynes",
  "best breakfast Milton Keynes",
  "breakfast near me Milton Keynes",
  "all day breakfast Milton Keynes",

  "halal restaurant Milton Keynes",
  "best halal restaurant Milton Keynes",
  "halal food Milton Keynes",
  "halal dining Milton Keynes",
  "halal brunch Milton Keynes",
  "halal breakfast Milton Keynes",
  "halal dinner Milton Keynes",
  "halal lunch Milton Keynes",
  "halal menu Milton Keynes",

  "Middle Eastern restaurant Milton Keynes",
  "Middle Eastern food Milton Keynes",
  "Middle Eastern brunch Milton Keynes",
  "Mediterranean restaurant Milton Keynes",
  "Mediterranean food Milton Keynes",
  "Mediterranean brunch Milton Keynes",
  "Arabic restaurant Milton Keynes",
  "Arabic food Milton Keynes",
  "Arabic brunch Milton Keynes",
  "Arabic French fusion café Milton Keynes",
  "French Arabic fusion restaurant Milton Keynes",

  "pistachio desserts Milton Keynes",
  "pistachio café Milton Keynes",
  "pistachio latte Milton Keynes",
  "pistachio croissant Milton Keynes",
  "pistachio pastries Milton Keynes",
  "pistachio cake Milton Keynes",
  "Arabic desserts Milton Keynes",
  "French pastries Milton Keynes",
  "dessert café Milton Keynes",

  "family restaurant Milton Keynes",
  "family brunch Milton Keynes",
  "kids menu Milton Keynes",
  "kids friendly café Milton Keynes",
  "kids friendly restaurant Milton Keynes",
  "family dining Milton Keynes",

  "restaurants Milton Keynes",
  "best restaurants Milton Keynes",
  "places to eat Milton Keynes",
  "food near me Milton Keynes",
  "restaurant near me Milton Keynes",
  "lunch Milton Keynes",
  "dinner Milton Keynes",

  "Central Milton Keynes café",
  "Central Milton Keynes brunch",
  "Central Milton Keynes halal restaurant",
  "CMK café",
  "CMK brunch",
  "CMK halal restaurant",
  "MK9 café",
  "MK9 brunch",
  "MK9 halal restaurant",
  "The Hub Milton Keynes restaurants",
];

export const pageSpecificKeywords = {
  menu: [
    "Nour Maison food menu",
    "Nour Maison restaurant menu",
    "brunch menu Milton Keynes",
    "breakfast menu Milton Keynes",
    "halal menu Milton Keynes",
    "Arabic brunch Milton Keynes",
    "Middle Eastern brunch Milton Keynes",
    "Mediterranean brunch Milton Keynes",
    "Lebanese mezze Milton Keynes",
    "Turkish breakfast Milton Keynes",
    "Egyptian breakfast Milton Keynes",
    "French brunch Milton Keynes",
    "signature dishes Milton Keynes",
    "chef crafted meals Milton Keynes",
    "sweet and savory brunch Milton Keynes",
    "halal breakfast menu Milton Keynes",
    "halal brunch menu Milton Keynes",
    "halal lunch menu Milton Keynes",
    "halal dinner menu Milton Keynes",
    "best halal menu Milton Keynes",
  ],

  booking: [
    "book Nour Maison",
    "Nour Maison booking",
    "book table Milton Keynes",
    "restaurant booking Milton Keynes",
    "brunch booking Milton Keynes",
    "book brunch Milton Keynes",
    "halal restaurant booking Milton Keynes",
    "family restaurant booking Milton Keynes",
    "romantic dinner booking Milton Keynes",
    "date night restaurant Milton Keynes",
    "birthday brunch Milton Keynes",
    "celebration dinner Milton Keynes",
    "special occasions Milton Keynes",
    "business brunch Milton Keynes",
    "premium dining booking Milton Keynes",
    "best restaurant booking Milton Keynes",
    "afternoon tea booking Milton Keynes",
    "halal afternoon tea booking Milton Keynes",
    "best brunch booking Milton Keynes",
    "book halal restaurant Milton Keynes",
  ],

  contactUs: [
    "Nour Maison contact",
    "contact Nour Maison",
    "Nour Maison Milton Keynes",
    "Nour Maison email",
    "Nour Maison phone",
    "restaurant contact Milton Keynes",
    "halal restaurant Milton Keynes contact",
    "reservation contact Nour Maison",
    "Nour Maison address",
    "get directions Nour Maison",
    "restaurant enquiries UK",
    "events booking Nour Maison",

    "Nour Maison location",
    "contact Nour Maison Milton Keynes",
    "café contact Milton Keynes",
    "halal restaurant near me Milton Keynes",
    "brunch near Central Milton Keynes",
    "café near Central Milton Keynes",
    "coffee shop near MK9",
    "restaurant near MK10",
    "food near me Milton Keynes",
    "places to eat near me Milton Keynes",
    "Nour Maison opening hours",
    "Nour Maison reservations",
    "Nour Maison near me",
    "Nour Maison Central Milton Keynes",
    "Nour Maison CMK",
    "best café near Central Milton Keynes",
    "best halal restaurant near me Milton Keynes",
  ],

  aboutUs: [
    "Nour Maison restaurant",
    "halal French food Milton Keynes",
    "Middle Eastern café UK",
    "French Middle Eastern fusion cuisine",
    "Chef Mo G restaurant",
    "Chef Mo G Nour Maison",
    "Chef-owned restaurants UK",
    "family-owned halal restaurant UK",
    "family brasserie Milton Keynes",
    "halal Mediterranean dining",
    "halal dining experience Milton Keynes",
    "halal artisan food UK",
    "halal gourmet café",
    "Milton Keynes café with story",
    "restaurant founded by chef",
    "halal food with heritage",
    "halal food with history",
    "Nour Maison story",
    "origin of Nour Maison",
    "our story Nour Maison",
    "halal fine dining UK",
    "halal brasserie",
    "Middle Eastern flavors UK",
    "French café with halal menu",
    "halal brunch restaurant",
    "about Chef Mo G",
    "culinary fusion story UK",
    "Chef-inspired halal restaurant",
    "family roots halal food",
    "brasserie with cultural fusion",
    "about Nour Maison",
    "halal food innovation",
    "Chef Mo G biography",
    "meet the chef Milton Keynes",
    "Nour Maison culinary roots",
    "halal food crafted with love",
    "Chef Mo G Middle Eastern cuisine",
    "halal hospitality",
    "Nour Maison halal vision",
    "modern halal brasserie",
    "French and Middle Eastern café",
    "chef-driven halal menu",
    "halal comfort food Milton Keynes",
    "restaurant with family values",
    "halal food culture UK",
    "halal restaurant journey UK",
    "Milton Keynes food culture",
    "halal food storytelling",
    "artisanal halal food UK",
    "halal home-style cooking",
    "brasserie heritage UK",
    "halal café with tradition",
    "fusion cuisine backstory UK",

    "about Nour Maison",
    "Nour Maison restaurant Milton Keynes",
    "Arabic French fusion restaurant Milton Keynes",
    "Mediterranean dining Milton Keynes",
    "Middle Eastern food Milton Keynes",
    "authentic Arabic food Milton Keynes",
    "French inspired café Milton Keynes",
    "premium café experience Milton Keynes",
    "luxury dining Milton Keynes",
    "modern restaurant Milton Keynes",
    "family friendly café Milton Keynes",
    "elegant restaurant Milton Keynes",
    "unique food experience Milton Keynes",
    "artisan food Milton Keynes",
  ],

  services: [
    "Nour Maison services",
    "Nour Maison events",
    "private events Milton Keynes",
    "birthday venue Milton Keynes",
    "corporate events Milton Keynes",
    "halal catering Milton Keynes",
    "restaurant events venue MK",
    "celebrations at Nour Maison",
    "family events Milton Keynes",
    "Afternoon Tea",
    "Baby Shower",
    "Gender Reveal",
    "Birthday Party",
    "Anniversaries",
    "Special Events",
    "Private Events",
    "Celebrations",

    "Elegant celebration",
    "Beautifully arranged gathering",
    "Magical moment",
    "Warm atmosphere",
    "Stunning decorations",
    "Exciting atmosphere",
    "Fun-filled party",
    "Elegant ambiance",
    "Cozy celebration",

    "Cherish forever",
    "Unforgettable memories",
    "Lasting memories",
    "Special milestone",
    "Love and joy",
    "Delightful memories",
    "Feels like love",
    "Tastes like adventure",

    "Baby celebration",
    "Family gathering",
    "Friends celebration",
    "Little one arrival",
    "Birthday celebration",
    "Couple anniversaries",

    "Afternoon tea experience",
    "Baby shower venue",
    "Gender reveal party venue",
    "Birthday party venue",
    "Anniversary celebration venue",
    "Elegant event space",
    "Celebration cafe",
    "Restaurant events",

    "restaurant services Milton Keynes",
    "café services Milton Keynes",
    "brunch service Milton Keynes",
    "family dining service Milton Keynes",
    "private dining Milton Keynes",
    "corporate brunch Milton Keynes",
    "business brunch Milton Keynes",
    "celebration dining Milton Keynes",
    "birthday brunch Milton Keynes",
    "romantic dining Milton Keynes",
    "premium restaurant service Milton Keynes",
    "halal dining service Milton Keynes",
    "luxury café service Milton Keynes",
    "event dining Milton Keynes",
    "afternoon tea service Milton Keynes",
    "family café service Milton Keynes",
    "best café service Milton Keynes",
    "halal restaurant service Milton Keynes",
    "premium brunch service Milton Keynes",
  ],

  afternoonTeaMenu: [
    "best afternoon tea Milton Keynes",
    "afternoon tea near me",
    "halal afternoon tea Milton Keynes",
    "Nour Maison afternoon tea",
    "afternoon tea Milton Keynes",
    "French patisserie Milton Keynes",
    "Middle Eastern afternoon tea",
    "afternoon tea menu UK",
    "halal afternoon tea UK",
    "afternoon tea MK",
    "luxury afternoon tea Milton Keynes",
    "afternoon tea for celebrations",
    "birthday afternoon tea Milton Keynes",
    "Nour Maison café menu",
    "sweet treats and savoury bites",
    "fusion afternoon tea",
    "elegant afternoon tea experience",

    "afternoon tea menu Milton Keynes",
    "French afternoon tea Milton Keynes",
    "Arabic afternoon tea Milton Keynes",
    "pistachio afternoon tea Milton Keynes",
    "French pastries afternoon tea",
    "Arabic desserts afternoon tea",
    "family afternoon tea Milton Keynes",
    "premium tea Milton Keynes café",
    "cakes Milton Keynes",
    "dessert café Milton Keynes",
    "best halal afternoon tea Milton Keynes",
    "afternoon tea near me Milton Keynes",
    "best afternoon tea near me Milton Keynes",
    "halal afternoon tea menu Milton Keynes",
    "pistachio desserts afternoon tea Milton Keynes",
  ],

  afternoonTeaBooking: [
    "Afternoon Tea Milton Keynes",
    "Book Afternoon Tea",
    "Nour Maison Afternoon Tea",
    "halal afternoon tea",
    "French afternoon tea UK",
    "Middle Eastern afternoon tea",
    "afternoon tea booking",
    "halal high tea Milton Keynes",
    "best afternoon tea MK",
    "afternoon tea reservation",
    "Nour Maison booking",
    "halal patisserie",
    "afternoon tea experience",
    "Book Afternoon Tea online",
    "Afternoon Tea reservation UK",

    "book afternoon tea Milton Keynes",
    "Nour Maison afternoon tea booking",
    "afternoon tea reservation Milton Keynes",
    "halal afternoon tea booking Milton Keynes",
    "luxury afternoon tea booking Milton Keynes",
    "family afternoon tea booking Milton Keynes",
    "birthday afternoon tea Milton Keynes",
    "special occasion afternoon tea Milton Keynes",
    "French pastries booking Milton Keynes",
    "dessert booking Milton Keynes",
    "tea and cakes Milton Keynes",
    "premium afternoon tea Milton Keynes",
    "book tea table Milton Keynes",
    "afternoon tea near me Milton Keynes",
    "best tea café Milton Keynes",
    "best afternoon tea booking Milton Keynes",
    "book halal afternoon tea Milton Keynes",
    "afternoon tea café Milton Keynes",
    "best halal afternoon tea booking Milton Keynes",
    "luxury tea booking Milton Keynes",
  ],

  roastMenu: [
    "Nour Maison roast dinner",
    "halal roast dinner",
    "French Arabic fusion roast",
    "Nour Maison café menu",
    "British roast with Arabic twist",

    "roast dinner Milton Keynes",
    "Nour Maison roast menu",
    "halal roast dinner Milton Keynes",
    "Sunday roast Milton Keynes",
    "Arabic roast dinner Milton Keynes",
    "Middle Eastern roast Milton Keynes",
    "premium roast Milton Keynes",
    "family Sunday meals Milton Keynes",
    "Sunday brunch Milton Keynes",
    "best roast Milton Keynes",
    "halal Sunday roast Milton Keynes",
    "roast dinner near me Milton Keynes",
    "luxury roast dinner Milton Keynes",
    "Mediterranean roast Milton Keynes",
    "Sunday dining Milton Keynes",
    "best Sunday roast Milton Keynes",
    "best halal roast dinner Milton Keynes",
    "halal roast menu Milton Keynes",
    "Arabic Sunday roast Milton Keynes",
    "family roast dinner Milton Keynes",
  ],

  kidsMenu: [
    "Nour Maison kids menu",
    "kids menu",
    "family friendly cafe",
    "healthy kids meals",
    "kid friendly cafe",
    "children meals",
    "Milton Keynes kids menu",
    "halal kids menu",

    "kids menu Milton Keynes",
    "children menu Milton Keynes",
    "kids meals Milton Keynes",
    "family café Milton Keynes",
    "family brunch Milton Keynes",
    "kids friendly restaurant Milton Keynes",
    "kids friendly café Milton Keynes",
    "toddler friendly café Milton Keynes",
    "healthy kids meals Milton Keynes",
    "kids desserts Milton Keynes",
    "kids brunch Milton Keynes",
    "family restaurant with kids menu Milton Keynes",
    "children friendly café Milton Keynes",
    "family dining Milton Keynes",
    "best kids menu Milton Keynes",
    "best family café Milton Keynes",
    "best kids friendly restaurant Milton Keynes",
    "halal kids menu Milton Keynes",
    "kids afternoon tea Milton Keynes",
  ],

  eidAlAdhaDinnerMenuMiltonKeynes: [
    "Eid Al-Adha dinner Milton Keynes",
    "Eid Adha menu Milton Keynes 2026",
    "Halal Eid dinner Milton Keynes",
    "Eid Al-Adha restaurant MK",
    "Confit lamb neck Milton Keynes",
    "Smoked Lahma MK",
    "Fatteh Masri Milton Keynes",
    "Halal fine dining Milton Keynes",
    "Family Eid dinner Milton Keynes",
    "Eid Mubarak dinner Milton Keynes",

    "Eid Al Adha dinner Milton Keynes",
    "Eid menu Milton Keynes",
    "Nour Maison Eid menu",
    "halal Eid dinner Milton Keynes",
    "Eid family dinner Milton Keynes",
    "Arabic dinner Milton Keynes",
    "Middle Eastern dinner Milton Keynes",
    "Mediterranean dinner Milton Keynes",
    "halal dinner Milton Keynes",
    "Arabic grill Milton Keynes",
    "Middle Eastern grill Milton Keynes",
    "family Eid meal Milton Keynes",
    "Eid celebration restaurant Milton Keynes",
    "luxury Eid dining Milton Keynes",
    "Eid restaurant Milton Keynes",
    "best Eid dinner Milton Keynes",
    "halal Eid menu Milton Keynes",
    "best halal Eid dinner Milton Keynes",
    "Eid restaurant booking Milton Keynes",
    "Eid family restaurant Milton Keynes",
  ],

  christmasMenu: [
    "Nour Maison Christmas menu",
    "Christmas dinner London",
    "festive menu London",
    "four course Christmas meal",
    "Arabic French fusion Christmas",
    "holiday menu nour maison",
    "Christmas roast dinner café",
    "Nour Maison festive edition",

    "Christmas menu Milton Keynes",
    "Christmas brunch Milton Keynes",
    "Christmas dinner Milton Keynes",
    "Christmas lunch Milton Keynes",
    "halal Christmas menu Milton Keynes",
    "Christmas desserts Milton Keynes",
    "festive dining Milton Keynes",
    "festive brunch Milton Keynes",
    "Christmas roast Milton Keynes",
    "winter drinks Milton Keynes",
    "pistachio Christmas desserts Milton Keynes",
    "family Christmas dining Milton Keynes",
    "Christmas café Milton Keynes",
    "Christmas restaurant Milton Keynes",
    "best Christmas menu Milton Keynes",
    "halal Christmas dinner Milton Keynes",
    "halal Christmas brunch Milton Keynes",
    "best festive dining Milton Keynes",
    "Christmas afternoon tea Milton Keynes",
  ],

  menuGallery: [
    "Nour Maison dessert menu",
    "halal desserts Milton Keynes",
    "French pastries Milton Keynes",
    "Middle Eastern sweets",
    "cakes Milton Keynes",
    "pancakes Milton Keynes",
    "halal cafe Milton Keynes",

    "Nour Maison menu gallery",
    "food gallery Milton Keynes",
    "brunch gallery Milton Keynes",
    "dessert gallery Milton Keynes",
    "pistachio dessert gallery Milton Keynes",
    "Arabic food photos Milton Keynes",
    "Middle Eastern food photos Milton Keynes",
    "Mediterranean food gallery Milton Keynes",
    "French pastries gallery Milton Keynes",
    "premium food presentation Milton Keynes",
    "instagrammable food Milton Keynes",
    "luxury brunch photos Milton Keynes",
    "restaurant dishes Milton Keynes",
    "café food gallery Milton Keynes",
    "best food experience Milton Keynes",
  ],

  gallery: [
    "Nour Maison gallery",
    "Nour Maison photos",
    "Nour Maison food gallery",
    "Nour Maison Milton Keynes",
    "restaurant ambiance photos",
    "elegant restaurant interiors",
    "artisanal food photography",
    "French Middle Eastern restaurant",
    "halal restaurant Milton Keynes",
    "Instagrammable restaurants Milton Keynes",
    "beautiful restaurants in Milton Keynes",
    "restaurant gallery Milton Keynes",
    "brunch spots Milton Keynes",

    "restaurant gallery Milton Keynes",
    "café interior Milton Keynes",
    "luxury café interior Milton Keynes",
    "elegant restaurant photos Milton Keynes",
    "brunch photos Milton Keynes",
    "pistachio desserts photos Milton Keynes",
    "French pastries photos Milton Keynes",
    "Arabic desserts photos Milton Keynes",
    "family dining photos Milton Keynes",
    "modern café photos Milton Keynes",
    "stylish café Milton Keynes",
    "cozy café Milton Keynes",
    "instagrammable café Milton Keynes",
  ],

  ramadanIftarMenuMiltonKeynes: [
    "Best Iftar Milton Keynes",
    "Best Iftar menu in Milton Keynes",
    "Iftar near me",
    "Halal Iftar near me Milton Keynes",
    "Family Iftar Milton Keynes",
    "Halal Iftar Restaurant Milton Keynes",
    "Iftar Menu Milton Keynes",
    "Iftar restaurant near me",
    "Halal Ramadan dinner",
    "Ramadan restaurant MK",
    "Halal restaurant Ramadan MK",
    "Iftar Milton Keynes",
    "Ramadan dining Milton Keynes",
    "5 course Iftar menu UK",
    "Halal restaurant Milton Keynes",
    "Ramadan 2026 Milton Keynes",
    "Middle Eastern restaurant MK",
    "Where to break fast Milton Keynes",
    "Iftar deals Milton Keynes",
    "Ramadan special menu MK",
    "Best Ramadan restaurant Milton Keynes",

    "Ramadan iftar Milton Keynes",
    "Nour Maison Ramadan menu",
    "iftar menu Milton Keynes",
    "halal iftar Milton Keynes",
    "Ramadan dinner Milton Keynes",
    "Arabic iftar Milton Keynes",
    "Middle Eastern iftar Milton Keynes",
    "family iftar Milton Keynes",
    "Ramadan restaurant Milton Keynes",
    "iftar booking Milton Keynes",
    "halal Ramadan menu Milton Keynes",
    "Mediterranean iftar Milton Keynes",
    "Ramadan desserts Milton Keynes",
    "Arabic sweets Ramadan Milton Keynes",
    "best Ramadan iftar Milton Keynes",
    "best halal iftar Milton Keynes",
    "Ramadan family restaurant Milton Keynes",
    "Ramadan iftar booking Milton Keynes",
    "halal iftar booking Milton Keynes",
  ],

  store: [
    "Nour Maison store",
    "Nour Maison gift cards",
    "store and gift cards",
    "restaurant gift cards UK",
    "halal dining gifts",
    "gift ideas Milton Keynes",
    "buy gift cards Milton Keynes",
    "halal restaurant gift cards",
    "French Middle Eastern restaurant gift card",
    "brunch gift vouchers UK",
    "birthday restaurant gift card",
    "fine dining gift card",
    "halal dinner gift",
    "corporate dining gift cards",
    "restaurant e-gift card",
    "gift card for food lovers",
    "dining experience gift voucher UK",
    "anniversary restaurant gift",
    "restaurant gift voucher Milton Keynes",
    "halal restaurant voucher UK",
    "artisan food store UK",
    "Nour Maison products",
    "branded restaurant merchandise",
    "restaurant souvenirs",
    "Middle Eastern spice blends",
    "French café products",
    "luxury food boxes UK",
    "gourmet items Milton Keynes",
    "halal pantry products",
    "brunch boxes UK",
    "restaurant food gifts UK",
    "where to buy gift cards Milton Keynes",
    "halal gift ideas in UK",
    "Milton Keynes gift shop",
    "shop local halal gifts",
    "halal food gifts near me",
    "restaurant gift ideas UK",
    "elegant restaurant gifts",
    "gift cards and artisan goods",
    "online store for halal products",
    "Milton Keynes artisan store",
    "gift a halal brunch experience",
    "shop halal gifts online UK",
    "Nour Maison gift shop",
    "luxury gift cards Milton Keynes",
    "halal brunch gift card Milton Keynes",
    "restaurant gifts Milton Keynes",
    "premium dining gifts Milton Keynes",
  ],

  giftCards: [
    "Nour Maison gift cards",
    "Nour Maison gift card",
    "Nour Maison gift vouchers",
    "Nour Maison dining voucher",
    "gift cards Milton Keynes",
    "restaurant gift cards Milton Keynes",
    "halal restaurant gift cards Milton Keynes",
    "brunch gift card Milton Keynes",
    "afternoon tea gift card Milton Keynes",
    "dining gift voucher Milton Keynes",
    "luxury restaurant gift card",
    "premium dining gift card",
    "birthday gift card Milton Keynes",
    "anniversary gift card Milton Keynes",
    "corporate gift cards Milton Keynes",
    "food lover gift card",
    "restaurant voucher Milton Keynes",
    "halal dining voucher UK",
    "French Middle Eastern gift card",
    "gift a brunch experience",
    "gift a halal dining experience",
    "Nour Maison e gift card",
    "online gift card restaurant UK",
    "best restaurant gift card Milton Keynes",
  ],

  createGiftPage: [
    "create Nour Maison gift card",
    "create gift card",
    "personalised gift card",
    "custom restaurant gift card",
    "custom dining voucher",
    "personalised restaurant voucher",
    "buy Nour Maison gift card",
    "send Nour Maison gift card",
    "send restaurant gift card",
    "online gift card Milton Keynes",
    "restaurant e gift card Milton Keynes",
    "halal restaurant e gift card",
    "birthday dining voucher",
    "anniversary dining voucher",
    "brunch gift voucher",
    "afternoon tea gift voucher",
    "luxury food gift card",
    "gift card checkout",
    "gift card form",
    "Nour Maison gift card online",
    "personalised halal dining gift",
    "send halal brunch gift",
    "create restaurant voucher UK",
    "digital dining gift card",
  ],

  becomeAMember: [
    "Nour Maison membership",
    "become a member Nour Maison",
    "Nour Maison member discount",
    "Nour Maison welcome discount",
    "Nour Maison 10% off",
    "restaurant membership Milton Keynes",
    "café membership Milton Keynes",
    "brunch discount Milton Keynes",
    "halal restaurant discount Milton Keynes",
    "Nour Maison offers",
    "Nour Maison rewards",
    "Nour Maison sign up",
    "join Nour Maison",
    "restaurant offers Milton Keynes",
    "café offers Milton Keynes",
    "halal dining offers Milton Keynes",
    "new customer discount Milton Keynes",
    "welcome discount restaurant",
    "10% discount restaurant Milton Keynes",
    "dining discount Milton Keynes",
    "special offers Milton Keynes café",
    "Nour Maison family",
    "join Nour Maison family",
    "first visit discount",
    "restaurant newsletter Milton Keynes",
  ],
  blog: [
    "Nour Maison blog",
    "Nour Maison lifestyle",
    "Nour Maison articles",
    "Nour Maison insights",
    "Nour Maison inspiration",
    "Nour Maison design blog",
    "Nour Maison decor tips",
    "lifestyle blogs",
    "modern lifestyle blog",
    "creative living tips",
    "mindful living",
    "balanced lifestyle ideas",
    "wellness and lifestyle",
    "personal growth blog",
    "elegant lifestyle ideas",
    "luxury lifestyle tips",
    "living well daily",
    "smart living blog",
    "lifestyle for modern homes",
    "home inspiration",
    "interior design tips",
    "home styling blog",
    "modern home ideas",
    "small space decorating tips",
    "luxury home ideas",
    "decor ideas",
    "home decor blog",
    "furniture styling tips",
    "elevated home spaces",
    "design for everyday living",
    "home improvement tips",
    "interior styling guide",
    "daily inspiration blog",
    "inspirational articles",
    "tips and ideas blog",
    "home and lifestyle articles",
    "read lifestyle tips online",
    "design tips for home",
    "interior decor blog UK",
    "food and lifestyle blog",
    "blog for home lovers",
    "blog for creative living",
    "blog for cozy living",
    "blog on interior trends",
    "read about lifestyle online",
    "design inspiration Milton Keynes",
    "UK home and lifestyle blog",
    "trending decor blog",
    "luxury interiors blog UK",
    "wellness lifestyle blog UK",
    "French style interiors blog",
    "stylish living ideas",

    "Nour Maison blogs",
    "Nour Maison food blog",
    "Nour Maison restaurant blog",
    "halal restaurant blog Milton Keynes",
    "halal dining blog Milton Keynes",
    "brunch blog Milton Keynes",
    "afternoon tea blog Milton Keynes",
    "Milton Keynes food blog",
    "restaurant articles Milton Keynes",
    "café blog Milton Keynes",
    "French Middle Eastern food blog",
    "Mediterranean food blog UK",
    "halal food articles UK",
    "family dining blog Milton Keynes",
    "dessert blog Milton Keynes",
    "pistachio desserts blog",
    "restaurant news Milton Keynes",
    "dining inspiration Milton Keynes",
    "food stories Milton Keynes",
  ],

  allBlogs: [
    "Halal restaurant blog Milton Keynes",
    "Halal dining guide MK",
    "Afternoon tea Milton Keynes",
    "Brunch ideas Milton Keynes",
    "Halal restaurant tips",
    "Fine dining blog UK",
    "Milton Keynes restaurant guide",
    "Halal food blog",
    "French Middle Eastern cuisine blog",
    "Nour Maison blog",
    "Best halal restaurants MK",
    "Restaurant recommendations Milton Keynes",
    "Halal afternoon tea guide",
    "Special occasions dining MK",
    "Family dining Milton Keynes",

    "Nour Maison all blogs",
    "Nour Maison articles",
    "Nour Maison restaurant articles",
    "all restaurant blogs Milton Keynes",
    "halal food guide Milton Keynes",
    "best brunch guide Milton Keynes",
    "afternoon tea guide Milton Keynes",
    "dessert guide Milton Keynes",
    "family restaurant guide Milton Keynes",
    "Milton Keynes café guide",
    "Middle Eastern food blog Milton Keynes",
    "Mediterranean food blog Milton Keynes",
    "French Arabic fusion blog",
    "halal brunch guide Milton Keynes",
    "restaurant tips Milton Keynes",
    "food inspiration Milton Keynes",
    "dining ideas Milton Keynes",
    "special occasion dining blog",
    "halal fine dining articles",
  ],

  portfolio: [
    "Nour Maison portfolio",
    "Nour Maison food portfolio",
    "Nour Maison restaurant portfolio",
    "Nour Maison culinary portfolio",
    "Nour Maison events portfolio",
    "restaurant portfolio Milton Keynes",
    "food photography Milton Keynes",
    "artisanal food portfolio",
    "culinary art Milton Keynes",
    "French Middle Eastern food portfolio",
    "halal restaurant portfolio",
    "brunch portfolio Milton Keynes",
    "dessert portfolio Milton Keynes",
    "pistachio desserts portfolio",
    "afternoon tea portfolio Milton Keynes",
    "event dining portfolio Milton Keynes",
    "restaurant gallery portfolio",
    "premium food presentation",
    "luxury restaurant visuals Milton Keynes",
    "elegant dining portfolio",
    "Nour Maison moments",
    "food and interiors portfolio",
    "restaurant experience portfolio",
    "best restaurant visuals Milton Keynes",
  ],

  checkout: [
    "NOUR MAISON checkout",
    "secure payment UK",
    "buy gift card online",
    "online payment Milton Keynes",
    "Dojo payment gateway",
    "NOUR MAISON gift card",
    "restaurant gift voucher",
    "Milton Keynes gift card",
    "secure online checkout",
    "encrypted payment",
    "halal restaurant gift card",
    "safe online payment",

    "Nour Maison payment",
    "Nour Maison secure checkout",
    "Nour Maison online checkout",
    "gift card checkout Milton Keynes",
    "restaurant voucher checkout",
    "secure gift card payment",
    "buy Nour Maison gift card online",
    "halal dining gift card checkout",
    "restaurant gift card payment UK",
    "online restaurant voucher payment",
    "safe gift card checkout UK",
    "encrypted checkout restaurant",
    "Visa Mastercard restaurant payment",
    "American Express restaurant payment",
  ],

  payment: [
    "Nour Maison payment",
    "NOUR MAISON payment",
    "Nour Maison secure payment",
    "restaurant payment Milton Keynes",
    "secure restaurant payment UK",
    "online payment Milton Keynes",
    "gift card payment Milton Keynes",
    "restaurant gift card payment",
    "dining voucher payment",
    "halal restaurant payment",
    "secure card payment restaurant",
    "Visa restaurant payment",
    "Mastercard restaurant payment",
    "PayPal restaurant payment",
    "safe online payment",
    "encrypted payment",
    "restaurant checkout payment",
    "Nour Maison order payment",
    "Nour Maison gift card payment",
    "easy payment Nour Maison",
  ],

  shippingCart: [
    "Nour Maison cart",
    "Nour Maison shopping cart",
    "Nour Maison shipping cart",
    "restaurant shopping cart",
    "gift card cart Milton Keynes",
    "restaurant gift card cart",
    "Nour Maison order summary",
    "Nour Maison online order",
    "Nour Maison basket",
    "halal restaurant cart",
    "gift voucher cart",
    "restaurant voucher cart",
    "online store cart Milton Keynes",
    "checkout cart Milton Keynes",
    "shopping cart Milton Keynes",
    "Nour Maison store cart",
    "Nour Maison gift voucher cart",
    "continue shopping Nour Maison",
    "restaurant products cart",
    "secure cart checkout",
  ],

  privacyPolicy: [
    "NOUR MAISON privacy policy",
    "privacy policy UK restaurant",
    "NOUR MAISON LTD",
    "data protection",
    "GDPR compliance",
    "personal data protection",
    "Milton Keynes restaurant privacy",
    "email marketing privacy",
    "cookie policy",
    "customer data security",
    "Nour Maison data privacy",
    "Nour Maison GDPR",
    "restaurant GDPR Milton Keynes",
    "UK GDPR restaurant policy",
    "restaurant privacy notice UK",
    "customer privacy restaurant UK",
    "Nour Maison customer data",
    "Nour Maison cookie privacy",
    "personal information restaurant UK",
    "privacy notice Milton Keynes",
    "data processing restaurant UK",
    "restaurant customer data protection",
    "Nour Maison legal policy",
  ],

  refundPolicy: [
    "NOUR MAISON refund policy",
    "refund policy UK restaurant",
    "NOUR MAISON LTD",
    "Nour Maison Café refund",
    "Milton Keynes restaurant refund",
    "online order refund",
    "food delivery refund",
    "restaurant refund policy UK",
    "order not delivered refund",
    "café refund policy",
    "Nour Maison refund",
    "Nour Maison order refund",
    "Nour Maison customer refund",
    "restaurant order refund Milton Keynes",
    "gift card refund policy",
    "online payment refund UK",
    "restaurant customer service refund",
    "refund request Nour Maison",
    "restaurant purchase refund",
    "café order refund Milton Keynes",
    "Nour Maison delivery refund",
    "Nour Maison legal refund policy",
  ],

  termsAndConditions: [
    "NOUR MAISON terms and conditions",
    "NOUR MAISON LTD",
    "Nour Maison Café terms",
    "restaurant terms UK",
    "Milton Keynes restaurant policy",
    "café terms and conditions",
    "online ordering terms",
    "reservation policy",
    "payment terms restaurant",
    "halal restaurant terms",
    "Nour Maison terms",
    "Nour Maison conditions",
    "Nour Maison legal terms",
    "restaurant booking terms Milton Keynes",
    "Nour Maison reservation policy",
    "restaurant payment policy UK",
    "gift card terms Nour Maison",
    "restaurant voucher terms",
    "online store terms UK",
    "Nour Maison service terms",
    "Nour Maison website terms",
    "Nour Maison order terms",
    "restaurant cancellation terms",
    "café policy Milton Keynes",
  ],
};

export const getPageKeywords = (page) => {
  return [
    ...new Set([
      ...(pageSpecificKeywords[page] || []),
      ...commonNourMaisonKeywords,
    ]),
  ];
};
