export default  [
  {
    id: 1,
    name: "Nour Maison GOOD MORNING CUP",
    category: "CUPS",
    price: 0,
    original_price: 0,
    discount: "20%",
    rating: 4,
    images: [
      "https://res.cloudinary.com/dbzn1y8rt/image/upload/w_1000,ar_1:1,c_fill,g_auto,e_art:hokusai/v1744573631/muftscgujz2hc3fmrwtg.avif",
      "https://res.cloudinary.com/dbzn1y8rt/image/upload/w_1000,ar_1:1,c_fill,g_auto,e_art:hokusai/v1744573695/auh4rhatfwyvkokdnmtx.avif",
    ],
  },
  {
    id: 2,
    name: "Nour Maison GOOD MORNING CUP",
    category: "CUPS",
    price: 0,
    original_price: 0,
    discount: "20%",
    rating: 4,
    images: [
      "https://res.cloudinary.com/dbzn1y8rt/image/upload/f_auto,q_auto/v1739871140/pwwv0fl91gfrcdgq85sk.avif",
      "https://res.cloudinary.com/dbzn1y8rt/image/upload/w_1000,ar_1:1,c_fill,g_auto,e_art:hokusai/v1744573695/auh4rhatfwyvkokdnmtx.avif",
    ],
  },
  {
    id: 3,
    name: "Nour Maison GOOD MORNING CUP",
    category: "CUPS",
    price: 0,
    original_price: 0,
    discount: "20%",
    rating: 4,
    images: [
      "https://res.cloudinary.com/dbzn1y8rt/image/upload/w_1000,ar_1:1,c_fill,g_auto,e_art:hokusai/v1744573631/muftscgujz2hc3fmrwtg.avif",
      "https://res.cloudinary.com/dbzn1y8rt/image/upload/w_1000,ar_1:1,c_fill,g_auto,e_art:hokusai/v1744573695/auh4rhatfwyvkokdnmtx.avif",
    ],
  },
  {
    id: 4,
    name: "Nour Maison GOOD MORNING CUP",
    category: "CUPS",
    price: 0,
    original_price: 0,
    discount: "20%",
    rating: 4,
    images: [
      "https://res.cloudinary.com/dbzn1y8rt/image/upload/w_1000,ar_1:1,c_fill,g_auto,e_art:hokusai/v1744573631/muftscgujz2hc3fmrwtg.avif",
      "https://res.cloudinary.com/dbzn1y8rt/image/upload/w_1000,ar_1:1,c_fill,g_auto,e_art:hokusai/v1744573695/auh4rhatfwyvkokdnmtx.avif",
    ],
  },
  {
    id: 5,
    name: "Nour Maison GOOD MORNING CUP",
    category: "CUPS",
    price: 0,
    original_price: 0,
    discount: "20%",
    rating: 4,
    images: [
      "https://res.cloudinary.com/dbzn1y8rt/image/upload/w_1000,ar_1:1,c_fill,g_auto,e_art:hokusai/v1744573631/muftscgujz2hc3fmrwtg.avif",
      "https://res.cloudinary.com/dbzn1y8rt/image/upload/w_1000,ar_1:1,c_fill,g_auto,e_art:hokusai/v1744573695/auh4rhatfwyvkokdnmtx.avif",
    ],
  },
  {
    id: 6,
    name: "Nour Maison GOOD MORNING CUP",
    category: "CUPS",
    price: 0,
    original_price: 0,
    discount: "20%",
    rating: 4,
    images: [
      "https://res.cloudinary.com/dbzn1y8rt/image/upload/w_1000,ar_1:1,c_fill,g_auto,e_art:hokusai/v1744573631/muftscgujz2hc3fmrwtg.avif",
      "https://res.cloudinary.com/dbzn1y8rt/image/upload/w_1000,ar_1:1,c_fill,g_auto,e_art:hokusai/v1744573695/auh4rhatfwyvkokdnmtx.avif",
    ],
  },
];
