export default  [
  {
    id: 1,
    name: "Nour Maison GOOD MORNING CUP",
    category: "CUPS",
    price: 0,
    original_price: 0,
    discount: "20%",
    rating: 4,
    images: [
      "https://res.cloudinary.com/dhebgz7qh/image/upload/v1767536319/muftscgujz2hc3fmrwtg_kshscq.avif",
      "https://res.cloudinary.com/dhebgz7qh/image/upload/v1767536366/auh4rhatfwyvkokdnmtx_w2hysi.avif",
    ],
  },
  {
    id: 2,
    name: "Nour Maison GOOD MORNING CUP",
    category: "CUPS",
    price: 0,
    original_price: 0,
    discount: "20%",
    rating: 4,
    images: [
      "https://res.cloudinary.com/dhebgz7qh/image/upload/v1767536398/pwwv0fl91gfrcdgq85sk_ornodn.webp",
      "https://res.cloudinary.com/dhebgz7qh/image/upload/v1767536366/auh4rhatfwyvkokdnmtx_w2hysi.avif",
    ],
  },
  {
    id: 3,
    name: "Nour Maison GOOD MORNING CUP",
    category: "CUPS",
    price: 0,
    original_price: 0,
    discount: "20%",
    rating: 4,
    images: [
      "https://res.cloudinary.com/dhebgz7qh/image/upload/v1767536319/muftscgujz2hc3fmrwtg_kshscq.avif",
      "https://res.cloudinary.com/dhebgz7qh/image/upload/v1767536366/auh4rhatfwyvkokdnmtx_w2hysi.avif",
    ],
  },
  {
    id: 4,
    name: "Nour Maison GOOD MORNING CUP",
    category: "CUPS",
    price: 0,
    original_price: 0,
    discount: "20%",
    rating: 4,
    images: [
      "https://res.cloudinary.com/dhebgz7qh/image/upload/v1767536319/muftscgujz2hc3fmrwtg_kshscq.avif",
      "https://res.cloudinary.com/dhebgz7qh/image/upload/v1767536366/auh4rhatfwyvkokdnmtx_w2hysi.avif",
    ],
  },
  {
    id: 5,
    name: "Nour Maison GOOD MORNING CUP",
    category: "CUPS",
    price: 0,
    original_price: 0,
    discount: "20%",
    rating: 4,
    images: [
      "https://res.cloudinary.com/dhebgz7qh/image/upload/v1767536319/muftscgujz2hc3fmrwtg_kshscq.avif",
      "https://res.cloudinary.com/dhebgz7qh/image/upload/v1767536366/auh4rhatfwyvkokdnmtx_w2hysi.avif",
    ],
  },
  {
    id: 6,
    name: "Nour Maison GOOD MORNING CUP",
    category: "CUPS",
    price: 0,
    original_price: 0,
    discount: "20%",
    rating: 4,
    images: [
      "https://res.cloudinary.com/dhebgz7qh/image/upload/v1767536319/muftscgujz2hc3fmrwtg_kshscq.avif",
      "https://res.cloudinary.com/dhebgz7qh/image/upload/v1767536366/auh4rhatfwyvkokdnmtx_w2hysi.avif",
    ],
  },
];
