// export const menu_1 = [
//   {
//     id: 1,
//     category: "Breakfast Croissant",
//     slogan: "Flaky, Buttery, Irresistible – A Bite of Paris in Every Layer!",
//     image:
//       "https://res.cloudinary.com/dhebgz7qh/image/upload/v1767529826/Jambon-Fromage_Croissant_tv5cmy.jpg",
//     items: [
//       {
//         name: "Jambon-Fromage Croissant",
//         price: 9.55,
//         description:
//           "Croissant filled with turkey ham, Dijon mustard, and Swiss cheese.",
//         allergens: ["Gluten", "Dairy", "Eggs", "Mustard"],
//         allergensItems: {
//           Celery: false,
//           "Cereals/Gluten": true,
//           Crustaceans: false,
//           Eggs: true,
//           Fish: false,
//           Lupin: false,
//           Milk: true,
//           Mustard: true,
//           Nuts: false,
//           Peanuts: false,
//           "Sesame Seeds": false,
//           Soya: false,
//           "Sulphur Dioxide": false,
//         },
//       },
//       {
//         name: "Scrambled Egg and Bacon Croissant",
//         price: 9.95,
//         description:
//           "Croissant, scrambled eggs, crispy bacon, and cheddar cheese.",
//         allergens: ["Gluten", "Dairy", "Eggs"],
//         allergensItems: {
//           Celery: false,
//           "Cereals/Gluten": true,
//           Crustaceans: false,
//           Eggs: true,
//           Fish: false,
//           Lupin: false,
//           Milk: true,
//           Mustard: false,
//           Nuts: false,
//           Peanuts: false,
//           "Sesame Seeds": false,
//           Soya: false,
//           "Sulphur Dioxide": false,
//         },
//       },
//       {
//         name: "Smoked Salmon Croissant",
//         image:
//           "https://res.cloudinary.com/dhebgz7qh/image/upload/v1767529845/Smoked_Salmon_Croissant_fpncmv.jpg",
//         price: 10.95,
//         description:
//           "Croissant, smoked salmon, cream cheese, capers, red onion, and rocket.",
//         allergens: ["Gluten", "Dairy", "Fish"],
//         allergensItems: {
//           Celery: false,
//           "Cereals/Gluten": true,
//           Crustaceans: false,
//           Eggs: true,
//           Fish: true,
//           Lupin: false,
//           Milk: true,
//           Mustard: false,
//           Nuts: false,
//           Peanuts: false,
//           "Sesame Seeds": false,
//           Soya: false,
//           "Sulphur Dioxide": false,
//         },
//       },
//       {
//         name: "Avocado and Egg Croissant",
//         price: 9.95,
//         description:
//           "Croissant, avocado, sunny-side up egg, tomatoes, and Harissa mayo.",
//         allergens: ["Gluten", "Dairy", "Eggs"],
//         allergensItems: {
//           Celery: false,
//           "Cereals/Gluten": true,
//           Crustaceans: false,
//           Eggs: true,
//           Fish: false,
//           Lupin: false,
//           Milk: true,
//           Mustard: false,
//           Nuts: false,
//           Peanuts: false,
//           "Sesame Seeds": false,
//           Soya: false,
//           "Sulphur Dioxide": false,
//         },
//       },
//       {
//         name: "Croissant Addict Special",
//         price: 11.95,
//         description:
//           "Seared croissant, poached eggs, smashed avocado, rocket, and parmesan cheese.",
//         allergens: ["Gluten", "Dairy", "Eggs"],
//         allergensItems: {
//           Celery: false,
//           "Cereals/Gluten": true,
//           Crustaceans: false,
//           Eggs: true,
//           Fish: false,
//           Lupin: false,
//           Milk: true,
//           Mustard: false,
//           Nuts: false,
//           Peanuts: false,
//           "Sesame Seeds": false,
//           Soya: false,
//           "Sulphur Dioxide": false,
//         },
//       },
//       {
//         name: " Butter Croissant",
//         price: 1.95,
//         description: "Butter croissant.",
//         allergensItems: {
//           Celery: false,
//           "Cereals/Gluten": true,
//           Crustaceans: false,
//           Eggs: true,
//           Fish: false,
//           Lupin: false,
//           Milk: true,
//           Mustard: false,
//           Nuts: false,
//           Peanuts: false,
//           "Sesame Seeds": false,
//           Soya: false,
//           "Sulphur Dioxide": false,
//         },
//       },
//       {
//         name: "Croissant Chocolate",
//         price: 1.95,
//         description: "",
//         allergensItems: {
//           Celery: false,
//           "Cereals/Gluten": true,
//           Crustaceans: false,
//           Eggs: true,
//           Fish: false,
//           Lupin: false,
//           Milk: true,
//           Mustard: false,
//           Nuts: true,
//           Peanuts: false,
//           "Sesame Seeds": false,
//           Soya: false,
//           "Sulphur Dioxide": false,
//         },
//       },
//       {
//         name: "Croissant Pistachio ",
//         image:
//           "https://res.cloudinary.com/dhebgz7qh/image/upload/v1767529834/Croissant_Pistachio_itmaea.jpg",
//         price: 5.95,
//         description: "",
//         allergens: ["Gluten", "Dairy", "Eggs", "Tree Nuts"],
//         allergensItems: {
//           Celery: false,
//           "Cereals/Gluten": true,
//           Crustaceans: false,
//           Eggs: true,
//           Fish: false,
//           Lupin: false,
//           Milk: true,
//           Mustard: false,
//           Nuts: true,
//           Peanuts: false,
//           "Sesame Seeds": false,
//           Soya: false,
//           "Sulphur Dioxide": false,
//         },
//       },
//       {
//         name: "Croissant Almond ",
//         image:
//           "https://res.cloudinary.com/dhebgz7qh/image/upload/v1767529834/Croissant_Pistachio_itmaea.jpg",
//         price: 3.95,
//         description: "",
//         allergensItems: {
//           Celery: false,
//           "Cereals/Gluten": true,
//           Crustaceans: false,
//           Eggs: true,
//           Fish: false,
//           Lupin: false,
//           Milk: true,
//           Mustard: false,
//           Nuts: true,
//           Peanuts: false,
//           "Sesame Seeds": false,
//           Soya: false,
//           "Sulphur Dioxide": false,
//         },
//       },
//     ],
//   },
//   {
//     id: 2,
//     category: "Toasts and Rolls",
//     slogan: "Golden, Toasted, and Stuffed with Love!",
//     image:
//       "https://res.cloudinary.com/dhebgz7qh/image/upload/v1767529840/Toasts_and_Rolls_u6inky.jpg",
//     items: [
//       {
//         name: "Truffle & Cheese Egg Rolls",
//         price: 9.95,
//         description:
//           "Soft and flaky rolls filled with creamy scrambled eggs, melted cheese, and a hint of truffle oil, topped with parmesan rocket.",
//         allergens: ["Gluten", "Dairy", "Eggs"],
//         allergensItems: {
//           Celery: false,
//           "Cereals/Gluten": true,
//           Crustaceans: false,
//           Eggs: true,
//           Fish: false,
//           Lupin: false,
//           Milk: true,
//           Mustard: false,
//           Nuts: false,
//           Peanuts: false,
//           "Sesame Seeds": false,
//           Soya: false,
//           "Sulphur Dioxide": false,
//         },
//       },
//       {
//         name: "Middle Eastern Roll",
//         price: 8.95,
//         description:
//           "Soft and flaky rolls filled with falafel, fresh vegetables, hummus, and drizzled with tahini sauce and sumac.",
//         allergens: ["Gluten", "Sesame"],
//         allergensItems: {
//           Celery: false,
//           "Cereals/Gluten": true,
//           Crustaceans: false,
//           Eggs: false,
//           Fish: false,
//           Lupin: false,
//           Milk: false,
//           Mustard: false,
//           Nuts: false,
//           Peanuts: false,
//           "Sesame Seeds": false,
//           Soya: false,
//           "Sulphur Dioxide": false,
//         },
//       },
//       {
//         name: "Lahma Brioche",
//         price: 12.95,
//         image:
//           "https://res.cloudinary.com/dhebgz7qh/image/upload/v1767529832/Lahma_Brioche_tayxif.webp",
//         description:
//           "Shredded smoked brisket, generously filled on a soft, buttery brioche toast, topped with crispy fried shallots and a touch of Harissa mayo.",
//         allergens: ["Gluten", "Dairy", "Eggs"],
//         allergensItems: {
//           Celery: false,
//           "Cereals/Gluten": true,
//           Crustaceans: false,
//           Eggs: true,
//           Fish: false,
//           Lupin: false,
//           Milk: true,
//           Mustard: false,
//           Nuts: false,
//           Peanuts: false,
//           "Sesame Seeds": false,
//           Soya: false,
//           "Sulphur Dioxide": false,
//         },
//       },
//       {
//         name: "Loaded Toast",
//         price: 10.95,
//         image:
//           "https://res.cloudinary.com/dhebgz7qh/image/upload/v1767529834/Loaded_Toast_nonqq8.webp",
//         description:
//           "Brioche toast filled with crispy hash browns, beef sausage, and beef bacon, drizzled with Harissa mayo, and garnished with fresh herbs.",
//         allergens: ["Gluten", "Dairy", "Eggs"],
//         allergensItems: {
//           Celery: false,
//           "Cereals/Gluten": true,
//           Crustaceans: false,
//           Eggs: true,
//           Fish: false,
//           Lupin: false,
//           Milk: true,
//           Mustard: false,
//           Nuts: false,
//           Peanuts: false,
//           "Sesame Seeds": false,
//           Soya: false,
//           "Sulphur Dioxide": false,
//         },
//       },
//     ],
//   },
//   {
//     id: 3,
//     category: "Classic Breakfast",
//     slogan: "Timeless Mornings, One Bite at a Time!",
//     image:
//       "https://res.cloudinary.com/dhebgz7qh/image/upload/v1767529834/Croissant_Pistachio_itmaea.jpg",
//     items: [
//       {
//         name: "Full English",
//         price: 12.95,
//         description:
//           "Fried eggs, beef sausages, crispy beef bacon, baked beans, grilled tomatoes, sautéed mushrooms, golden hash browns, and toast.",
//         allergens: ["Gluten", "Eggs"],
//         allergensItems: {
//           Celery: false,
//           "Cereals/Gluten": true,
//           Crustaceans: false,
//           Eggs: true,
//           Fish: false,
//           Lupin: false,
//           Milk: true,
//           Mustard: false,
//           Nuts: false,
//           Peanuts: false,
//           "Sesame Seeds": false,
//           Soya: false,
//           "Sulphur Dioxide": false,
//         },
//       },
//       {
//         name: "SpudBowl",
//         price: 11.95,
//         description:
//           "A bowl of crispy hash browns topped with poached eggs, smashed avocado, pickled onions, a drizzle of harissa mayo.",
//         allergens: ["Eggs", "Dairy"],
//         allergensItems: {
//           Celery: false,
//           "Cereals/Gluten": false,
//           Crustaceans: false,
//           Eggs: true,
//           Fish: false,
//           Lupin: false,
//           Milk: false,
//           Mustard: false,
//           Nuts: false,
//           Peanuts: false,
//           "Sesame Seeds": false,
//           Soya: false,
//           "Sulphur Dioxide": false,
//         },
//       },
//       {
//         name: "Turkish Breakfast",
//         price: 13.95,
//         image:
//           "https://res.cloudinary.com/dhebgz7qh/image/upload/v1767529845/Turkish_Breakfast_yrrguc.webp",
//         description:
//           "A vibrant selection of boiled eggs, feta cheese, olives, spicy sausage, tomatoes, cucumbers, honey butter, jam, and simit.",
//         allergens: ["Gluten", "Dairy", "Eggs", "Nuts"],
//         allergensItems: {
//           Celery: false,
//           "Cereals/Gluten": true,
//           Crustaceans: false,
//           Eggs: true,
//           Fish: false,
//           Lupin: false,
//           Milk: true,
//           Mustard: false,
//           Nuts: false,
//           Peanuts: false,
//           "Sesame Seeds": false,
//           Soya: false,
//           "Sulphur Dioxide": false,
//         },
//       },
//       {
//         name: "Middle Eastern Feast",
//         price: 14.95,
//         description:
//           "An array of Middle Eastern delights, including: baba ghanoush, fried boiled eggs, falafel, foul masri, chips, mix pickles, pita bread.",
//         allergens: ["Gluten", "Eggs", "Dairy", "Sesame"],
//         allergensItems: {
//           Celery: false,
//           "Cereals/Gluten": true,
//           Crustaceans: false,
//           Eggs: true,
//           Fish: false,
//           Lupin: false,
//           Milk: false,
//           Mustard: false,
//           Nuts: false,
//           Peanuts: false,
//           "Sesame Seeds": true,
//           Soya: false,
//           "Sulphur Dioxide": false,
//         },
//       },
//       {
//         name: "Classic Shakshuka",
//         image:
//           "https://res.cloudinary.com/dhebgz7qh/image/upload/v1767529819/Classic_Shakshuka_zntz65.jpg ",
//         price: 10.95,
//         description:
//           "Runny eggs in a rich tomato, pepper, and onion sauce, served with sourdough.",
//         allergens: ["Eggs", "Dairy", "Gluten"],
//         allergensItems: {
//           Celery: false,
//           "Cereals/Gluten": false,
//           Crustaceans: false,
//           Eggs: true,
//           Fish: false,
//           Lupin: false,
//           Milk: true,
//           Mustard: false,
//           Nuts: false,
//           Peanuts: false,
//           "Sesame Seeds": false,
//           Soya: false,
//           "Sulphur Dioxide": false,
//         },
//       },
//       {
//         name: "Pancake à la canadienne",
//         price: 14.95,
//         description:
//           "Fluffy pancakes, beef sausage, beef bacon, scrambled eggs topped with maple and fresh berries.",
//         allergens: ["Gluten", "Dairy", "Eggs"],
//         allergensItems: {
//           Celery: false,
//           "Cereals/Gluten": true,
//           Crustaceans: false,
//           Eggs: true,
//           Fish: false,
//           Lupin: false,
//           Milk: true,
//           Mustard: false,
//           Nuts: false,
//           Peanuts: false,
//           "Sesame Seeds": false,
//           Soya: false,
//           "Sulphur Dioxide": false,
//         },
//       },
//     ],
//   },
//   {
//     id: 4,
//     category: "Artisan Benedict",
//     slogan: "Eggsquisite Delights with a Gourmet Twist!",
//     image:
//       "https://res.cloudinary.com/dhebgz7qh/image/upload/v1767529804/Artisan_Benedict_tlnupg.jpg",
//     items: [
//       {
//         name: "Avo Tartine",
//         price: 10.95,
//         description:
//           "Smashed avocado, sliced radish, a drizzle of lemon vinaigrette, sprinkled with black seeds on a sourdough.",
//         allergens: ["Gluten", "Sesame"],
//         allergensItems: {
//           Celery: false,
//           "Cereals/Gluten": true,
//           Crustaceans: false,
//           Eggs: false,
//           Fish: false,
//           Lupin: false,
//           Milk: false,
//           Mustard: false,
//           Nuts: false,
//           Peanuts: false,
//           "Sesame Seeds": true,
//           Soya: false,
//           "Sulphur Dioxide": false,
//         },
//       },
//       {
//         name: "Eggs Benedict",
//         price: 10.95,
//         description:
//           "Classic poached eggs, beef bacon, and Harissa hollandaise on an English muffin.",
//         allergens: ["Gluten", "Eggs", "Dairy"],
//         allergensItems: {
//           Celery: false,
//           "Cereals/Gluten": true,
//           Crustaceans: false,
//           Eggs: true,
//           Fish: false,
//           Lupin: false,
//           Milk: true,
//           Mustard: false,
//           Nuts: false,
//           Peanuts: false,
//           "Sesame Seeds": false,
//           Soya: false,
//           "Sulphur Dioxide": false,
//         },
//       },
//       {
//         name: "Egg Royale",
//         image:
//           "https://res.cloudinary.com/dhebgz7qh/image/upload/v1767529825/Egg_Royale_whb5vh.jpg",
//         price: 12.95,
//         description:
//           "Poached eggs, smoked salmon, and Harissa hollandaise on an English muffin.",
//         allergens: ["Gluten", "Eggs", "Dairy", "Fish"],
//         allergensItems: {
//           Celery: false,
//           "Cereals/Gluten": true,
//           Crustaceans: false,
//           Eggs: true,
//           Fish: false,
//           Lupin: false,
//           Milk: true,
//           Mustard: false,
//           Nuts: false,
//           Peanuts: false,
//           "Sesame Seeds": false,
//           Soya: false,
//           "Sulphur Dioxide": false,
//         },
//       },
//       {
//         name: "Baba Ganoush Benedict",
//         price: 11.95,
//         description:
//           "Poached eggs, smoked aubergine puree, pickled beetroot, and Harissa hollandaise on a sourdough, sprinkled with sumac.",
//         allergens: ["Gluten", "Eggs", "Dairy"],
//         allergensItems: {
//           Celery: false,
//           "Cereals/Gluten": true,
//           Crustaceans: false,
//           Eggs: true,
//           Fish: false,
//           Lupin: false,
//           Milk: true,
//           Mustard: false,
//           Nuts: false,
//           Peanuts: false,
//           "Sesame Seeds": true,
//           Soya: false,
//           "Sulphur Dioxide": false,
//         },
//       },
//       {
//         name: "Goatacado",
//         price: 13.95,
//         description:
//           "Poached eggs, creamy goat cheese, avocado, and pickled onions with Harissa hollandaise on a sourdough.",
//         allergens: ["Gluten", "Eggs", "Dairy", "Nuts"],
//         allergensItems: {
//           Celery: false,
//           "Cereals/Gluten": true,
//           Crustaceans: false,
//           Eggs: true,
//           Fish: false,
//           Lupin: false,
//           Milk: true,
//           Mustard: false,
//           Nuts: false,
//           Peanuts: false,
//           "Sesame Seeds": false,
//           Soya: false,
//           "Sulphur Dioxide": false,
//         },
//       },
//       {
//         name: "Truffle Mushroom Benedict",
//         price: 13.95,
//         description:
//           "Caramelized onions, truffle-infused portobello mushroom, and cashew hollandaise on a sourdough.",
//         allergens: ["Gluten", "Eggs", "Dairy"],
//         allergensItems: {
//           Celery: false,
//           "Cereals/Gluten": true,
//           Crustaceans: false,
//           Eggs: false,
//           Fish: false,
//           Lupin: false,
//           Milk: false,
//           Mustard: false,
//           Nuts: false,
//           Peanuts: false,
//           "Sesame Seeds": false,
//           Soya: false,
//           "Sulphur Dioxide": false,
//         },
//       },
//     ],
//   },
//   {
//     id: 5,
//     category: "Signature Breakfast",
//     image:
//       "https://res.cloudinary.com/dhebgz7qh/image/upload/v1767529848/Waffle_Truffle_ako4il.jpg",
//     slogan: "Bold Flavors, Signature Perfection!",
//     items: [
//       {
//         name: "Waffle Truffle",
//         price: 13.95,
//         image:
//           "https://res.cloudinary.com/dhebgz7qh/image/upload/v1767529848/Waffle_Truffle_ako4il.jpg",
//         description:
//           "Waffles topped with brie cheese, figs, honey on a bed of sweet carrot purée, and a drizzle of truffle oil.",
//         allergens: ["Gluten", "Dairy", "Eggs"],
//         allergensItems: {
//           Celery: false,
//           "Cereals/Gluten": true,
//           Crustaceans: false,
//           Eggs: true,
//           Fish: false,
//           Lupin: false,
//           Milk: true,
//           Mustard: false,
//           Nuts: false,
//           Peanuts: false,
//           "Sesame Seeds": false,
//           Soya: false,
//           "Sulphur Dioxide": false,
//         },
//       },
//       {
//         name: "Croque Monsieur",
//         image:
//           "https://res.cloudinary.com/dhebgz7qh/image/upload/v1767529830/Croque_Monsieur_c2ptgy.jpg",
//         price: 13.95,
//         description:
//           "Toasted baked sourdough layered with turkey ham, creamy béchamel sauce, and melted Swiss cheese served with mix leaves.",
//         allergens: ["Gluten", "Dairy", "Eggs"],
//         allergensItems: {
//           Celery: false,
//           "Cereals/Gluten": true,
//           Crustaceans: false,
//           Eggs: false,
//           Fish: false,
//           Lupin: false,
//           Milk: true,
//           Mustard: false,
//           Nuts: false,
//           Peanuts: false,
//           "Sesame Seeds": false,
//           Soya: false,
//           "Sulphur Dioxide": false,
//         },
//       },
//       {
//         name: "French Toast",
//         image:
//           "https://res.cloudinary.com/dhebgz7qh/image/upload/v1767529828/French_Toast_h6n9lx.jpg",
//         price: 13.95,
//         description:
//           "Thick slices of brioche soaked in a cinnamon-vanilla-egg batter, served with berries.",
//         allergens: ["Gluten", "Dairy", "Eggs"],
//         allergensItems: {
//           Celery: false,
//           "Cereals/Gluten": true,
//           Crustaceans: false,
//           Eggs: true,
//           Fish: false,
//           Lupin: false,
//           Milk: true,
//           Mustard: false,
//           Nuts: true,
//           Peanuts: false,
//           "Sesame Seeds": false,
//           Soya: false,
//           "Sulphur Dioxide": false,
//         },
//       },
//       {
//         name: "Bacon Egg Brioche",
//         price: 11.95,
//         description:
//           "A soft brioche bed topped with crispy bacon, scrambled eggs, and a hint of cheddar cheese served with crispy leaves.",
//         allergens: ["Gluten", "Dairy", "Eggs"],
//         allergensItems: {
//           Celery: false,
//           "Cereals/Gluten": true,
//           Crustaceans: false,
//           Eggs: true,
//           Fish: false,
//           Lupin: false,
//           Milk: true,
//           Mustard: false,
//           Nuts: false,
//           Peanuts: false,
//           "Sesame Seeds": false,
//           Soya: false,
//           "Sulphur Dioxide": false,
//         },
//       },
//       {
//         name: "Nour’s Special Breakfast",
//         price: 13.95,
//         description:
//           "Crispy Turkish simit bread layered with sliced avocado and cream cheese, pureed chickpeas, and crushed walnuts, and a scattering of fresh seasonal fruit.",
//         allergens: ["Gluten", "Dairy", "Eggs", "Nuts"],
//         allergensItems: {
//           Celery: false,
//           "Cereals/Gluten": true,
//           Crustaceans: false,
//           Eggs: false,
//           Fish: false,
//           Lupin: false,
//           Milk: true,
//           Mustard: false,
//           Nuts: false,
//           Peanuts: false,
//           "Sesame Seeds": true,
//           Soya: false,
//           "Sulphur Dioxide": false,
//         },
//       },
//       {
//         name: "Foul Masri",
//         price: 10.95,
//         description:
//           "A classic Egyptian dish made with slow-cooked fava beans, seasoned with garlic, cumin, lemon juice, and olive oil. Served with warm pita bread and garnished with fresh herbs, diced tomatoes, and a drizzle of tahini.",
//         allergens: ["Gluten", "Dairy", "Eggs", "Nuts"],
//         allergensItems: {
//           Celery: false,
//           "Cereals/Gluten": false,
//           Crustaceans: false,
//           Eggs: false,
//           Fish: false,
//           Lupin: false,
//           Milk: true,
//           Mustard: false,
//           Nuts: false,
//           Peanuts: false,
//           "Sesame Seeds": false,
//           Soya: false,
//           "Sulphur Dioxide": false,
//         },
//       },
//       {
//         name: "Eggah Omelette",
//         price: 10.95,
//         description:
//           "A fluffy omelette with fresh herbs, spring onions, sautéed potato, and a hint of cumin. Topped with brie cheese.",
//         allergens: ["Gluten", "Dairy", "Eggs", "Nuts"],
//         allergensItems: {
//           Celery: false,
//           "Cereals/Gluten": false,
//           Crustaceans: false,
//           Eggs: true,
//           Fish: false,
//           Lupin: false,
//           Milk: true,
//           Mustard: false,
//           Nuts: false,
//           Peanuts: false,
//           "Sesame Seeds": false,
//           Soya: false,
//           "Sulphur Dioxide": false,
//         },
//       },
//     ],
//   },
//   {
//     category: "All-Day Brunch",
//     slogan: "Brunch O’Clock, Anytime You Crave",
//     image:
//       "https://res.cloudinary.com/dhebgz7qh/image/upload/v1767529834/Salads_krgtsh.jpg",
//     items: [
//       {
//         name: "Chicken Escalope",
//         price: 14.45,
//         description:
//           "Crispy, golden-breaded chicken breast served with creamy Parmesan sauce, mixed greens, and French fries.",
//         allergens: ["Gluten", "Dairy"],
//          allergensItems: {
//           Celery: false,
//           "Cereals/Gluten": true,
//           Crustaceans: false,
//           Eggs: true,
//           Fish: false,
//           Lupin: false,
//           Milk: true,
//           Mustard: false,
//           Nuts: false,
//           Peanuts: false,
//           "Sesame Seeds": false,
//           Soya: false,
//           "Sulphur Dioxide": false,
//         },
//       },
//       {
//         name: "Cheezy Split Burger (Smashed beef)",
//         price: 15.95,
//         description:
//           "A burger cut in half served on a sizzling skillet on top a pool of rich, melted cheese sauce with French fries.",
//         allergens: ["Gluten", "Dairy"],
//          allergensItems: {
//           Celery: false,
//           "Cereals/Gluten": true,
//           Crustaceans: false,
//           Eggs: false,
//           Fish: false,
//           Lupin: false,
//           Milk: true,
//           Mustard: false,
//           Nuts: false,
//           Peanuts: false,
//           "Sesame Seeds": false,
//           Soya: false,
//           "Sulphur Dioxide": false,
//         },
//       },
//       {
//         name: "Cheezy Split Burger (Chicken)",
//         price: 14.95,
//         description:
//           "Grilled chicken breast wrapped in a soft flatbread with sautéed mixed veg and algerienne sauce with French fries.",
//         allergens: ["Gluten", "Dairy"],
//          allergensItems: {
//           Celery: false,
//           "Cereals/Gluten": true,
//           Crustaceans: false,
//           Eggs: false,
//           Fish: false,
//           Lupin: false,
//           Milk: true,
//           Mustard: false,
//           Nuts: false,
//           Peanuts: false,
//           "Sesame Seeds": false,
//           Soya: false,
//           "Sulphur Dioxide": false,
//         },
//       },
//       {
//         name: "Poulet Wrap",
//         price: 14.95,
//         description:
//           "A burger cut in half served on a sizzling skillet on top a pool of rich, melted cheese sauce with French fries.",
//         allergens: ["Gluten", "Dairy"],
//          allergensItems: {
//           Celery: false,
//           "Cereals/Gluten": true,
//           Crustaceans: false,
//           Eggs: false,
//           Fish: false,
//           Lupin: false,
//           Milk: true,
//           Mustard: false,
//           Nuts: false,
//           Peanuts: false,
//           "Sesame Seeds": false,
//           Soya: false,
//           "Sulphur Dioxide": false,
//         },
//       },
//       {
//         name: "Fish and Chips",
//         price: 13.95,
//         description:
//           "Crispy, golden-battered cod served with perfectly seasoned chips and a side of tangy tartar sauce.",
//         allergens: ["Gluten", "Dairy"],
//          allergensItems: {
//           Celery: false,
//           "Cereals/Gluten": true,
//           Crustaceans: false,
//           Eggs: false,
//           Fish: false,
//           Lupin: false,
//           Milk: false,
//           Mustard: false,
//           Nuts: false,
//           Peanuts: false,
//           "Sesame Seeds": false,
//           Soya: false,
//           "Sulphur Dioxide": false,
//         },
//       },
//       {
//         name: "Nour’s Burger",
//         price: 16.95,
//         description:
//           "Tender pulled beef slow-cooked in a blend of spices, piled high on a toasted brioche bun. Topped with melted cheese, pickled onions, served with French fries.",
//         allergens: ["Gluten", "Dairy"],
//          allergensItems: {
//           Celery: false,
//           "Cereals/Gluten": true,
//           Crustaceans: false,
//           Eggs: true,
//           Fish: false,
//           Lupin: false,
//           Milk: true,
//           Mustard: false,
//           Nuts: false,
//           Peanuts: false,
//           "Sesame Seeds": false,
//           Soya: false,
//           "Sulphur Dioxide": false,
//         },
//       },
//       {
//         name: "Zaatar Pita Nachos",
//         price: 13.95,
//         description:
//           "Crispy pita chips dusted with zaatar spice, topped with grilled chicken, fresh herbs, tangy cheese sauce, pickled onions, and a drizzle of algerienne sauce.",
//         allergens: ["Gluten", "Dairy"],
//          allergensItems: {
//           Celery: false,
//           "Cereals/Gluten": true,
//           Crustaceans: false,
//           Eggs: true,
//           Fish: false,
//           Lupin: false,
//           Milk: true,
//           Mustard: false,
//           Nuts: false,
//           Peanuts: false,
//           "Sesame Seeds": false,
//           Soya: false,
//           "Sulphur Dioxide": false,
//         },
//       },
//     ],
//   },
//   {
//     id: 1001,
//     category: "CHEF SPECIAL",
//     slogan: "Crafted by the Chef, Served with Soul.",
//     image:
//       "https://res.cloudinary.com/dhebgz7qh/image/upload/v1767529838/The_Green_Smoothie_hkpuur.webp",
//     items: [
//       {
//         name: "Chicken Olive Tagine",
//         price: 21.95,
//         description:
//           "Slow-cooked chicken with green olives, preserved lemons, and Moroccan spices, served with fluffy couscous. A burst of North African flavor!",
//         allergens: ["Gluten"],
//         allergensItems: {
//           Celery: false,
//           "Cereals/Gluten": true,
//           Crustaceans: false,
//           Eggs: false,
//           Fish: false,
//           Lupin: false,
//           Milk: false,
//           Mustard: false,
//           Nuts: false,
//           Peanuts: false,
//           "Sesame Seeds": false,
//           Soya: false,
//           "Sulphur Dioxide": false,
//         },
//       },
//       {
//         name: "Barkouk Lamb Tagine",
//         price: 23.95,
//         description:
//           "Tender lamb slow-cooked with apricots, prunes, and warm spices saffron rice. Sweet meets savory perfection!",
//         allergens: [],
//         allergensItems: {
//           Celery: false,
//           "Cereals/Gluten": false,
//           Crustaceans: false,
//           Eggs: false,
//           Fish: false,
//           Lupin: false,
//           Milk: false,
//           Mustard: false,
//           Nuts: false,
//           Peanuts: false,
//           "Sesame Seeds": false,
//           Soya: false,
//           "Sulphur Dioxide": false,
//         },
//       },
//       {
//         name: "Beef Meatball Tagine",
//         price: 19.95,
//         description:
//           "Juicy spiced beef meatballs in a rich tomato sauce, topped with an egg and served with crusty bread for dipping. Comfort food with a kick!",
//         allergens: ["Gluten", "Eggs"],
//         allergensItems: {
//           Celery: false,
//           "Cereals/Gluten": true,
//           Crustaceans: false,
//           Eggs: true,
//           Fish: false,
//           Lupin: false,
//           Milk: false,
//           Mustard: false,
//           Nuts: false,
//           Peanuts: false,
//           "Sesame Seeds": false,
//           Soya: false,
//           "Sulphur Dioxide": false,
//         },
//       },
//       {
//         name: "Chicken Pastilla",
//         price: 18.95,
//         description:
//           "Flaky pastry stuffed with spiced chicken, almonds, and a touch of cinnamon, topped with a hint of caster sugar. A sweet and savory pie delight!",
//         allergens: ["Gluten", "Nuts"],
//         allergensItems: {
//           Celery: false,
//           "Cereals/Gluten": true,
//           Crustaceans: false,
//           Eggs: false,
//           Fish: false,
//           Lupin: false,
//           Milk: false,
//           Mustard: false,
//           Nuts: true,
//           Peanuts: false,
//           "Sesame Seeds": false,
//           Soya: false,
//           "Sulphur Dioxide": false,
//         },
//       },
//     ],
//   },
//   {
//     id: 6,
//     category: "Salads",
//     slogan: "Fresh, Crisp, and Full of Vibrant Goodness!",
//     image:
//       "https://res.cloudinary.com/dhebgz7qh/image/upload/v1767529834/Salads_krgtsh.jpg",
//     items: [
//       {
//         name: "Herb Feta and Olive Tabbouleh",
//         price: 9.95,
//         description:
//           "Fresh herbs, feta cheese, olives, and bulgur wheat, with a lemon dressing.",
//         allergens: ["Gluten", "Dairy"],
//       },
//       {
//         name: "Avocado Salad with Sumac",
//         price: 10.95,
//         description:
//           "Crispy mixed lettuce, sliced avocado, pomegranate, crushed walnuts, and Harissa mayo.",
//         allergens: ["Dairy", "Nuts"],
//       },
//     ],
//   },
//   {
//     id: 7,
//     category: "Coffee",
//     slogan: "Brewed to Perfection, Sipped with Passion.",
//     image:
//       "https://res.cloudinary.com/dhebgz7qh/image/upload/v1767529819/Coffee_y1u5ai.jpg",
//     items: [
//       { name: "Double Espresso", price: 2.65, allergens: [] },
//       { name: "Americano", price: 2.65, allergens: [] },
//       { name: "Macchiato", price: 2.75, allergens: ["Dairy"] },
//       { name: "Cortado", price: 3.45, allergens: ["Dairy"] },
//       { name: "Flat White", price: 3.45, allergens: ["Dairy"] },
//       { name: "Cappuccino", price: 3.65, allergens: ["Dairy"] },
//       {
//         name: "Latte",
//         image:
//           "https://res.cloudinary.com/dhebgz7qh/image/upload/v1767529831/Latte_c9jqf9.jpg",
//         price: 3.75,
//         allergens: ["Dairy"],
//       },
//       { name: "Mocha", price: 3.85, allergens: ["Dairy"] },
//     ],
//   },
//   {
//     id: 8,
//     category: "Filter Coffee",
//     slogan: "Pure, Slow, and Worth the Wait.",
//     items: [
//       { name: "V60 for One", price: 4.95, allergens: [] },
//       { name: "V60 for Share", price: 6.95, allergens: [] },
//     ],
//   },
//   {
//     id: 9,
//     category: "Not Coffee",
//     slogan: "Beyond Coffee, Beyond Ordinary.",
//     items: [
//       {
//         name: "Pot of Tea (English Breakfast / Earl Grey)",
//         price: 3.45,
//         allergens: [],
//       },
//       { name: "Decaf Tea", price: 2.95, allergens: [] },
//       { name: "Green Tea", price: 2.45, allergens: [] },
//       { name: "Chamomile Tea", price: 2.65, allergens: [] },
//       { name: "Peppermint Tea", price: 2.65, allergens: [] },
//       { name: "Berry Tea", price: 3.35, allergens: [] },
//       { name: "Chai Latte", price: 3.65, allergens: ["Dairy"] },
//       { name: "Hot Chocolate", price: 3.85, allergens: ["Dairy"] },
//     ],
//   },
//   {
//     id: 10,
//     category: "Bubble Tea",
//     slogan: "Sip, Pop, and Enjoy the Fun!",
//     items: [
//       {
//         name: "Pick Your Base - Watermelon, Strawberry & Raspberry, Peach & Passion",
//         price: 3.5,
//         allergens: [],
//       },
//       {
//         name: "Pick Your Bubbles - Mango, Passionfruit, Strawberry (per scoop)",
//         price: 0.5,
//         allergens: [],
//       },
//     ],
//   },
//   {
//     id: 11,
//     category: "Nour's Specialty Coffees",
//     slogan: "Where Tradition Meets a Twist of Magic.",
//     items: [
//       {
//         name: "Tiramisu Latte",
//         price: 6.55,
//         allergens: ["Gluten", "Dairy", "Eggs"],
//       },
//       {
//         name: "Blue Moon Latte (Hot/Iced)",
//         price: 6.55,
//         allergens: ["Dairy"],
//         image:
//           "https://res.cloudinary.com/dhebgz7qh/image/upload/v1767529835/Blue_Moon_Latte_katty1.webp",
//       },
//       {
//         name: "Crème Brûlée Latte (Hot/Iced)",
//         price: 6.55,
//         allergens: ["Dairy", "Eggs"],
//       },
//       {
//         name: "Pistachio and Rose Latte (Hot/Iced)",
//         price: 5.95,
//         allergens: ["Dairy", "Nuts"],
//       },
//       {
//         name: "Croissant Latte",
//         price: 5.95,
//         allergens: ["Gluten", "Dairy", "Eggs"],
//       },
//       {
//         name: "Halva Latte",
//         price: 5.95,
//         allergens: ["Dairy", "Sesame"],
//       },
//       {
//         name: "Baklava Latte",
//         image:
//           "https://res.cloudinary.com/dhebgz7qh/image/upload/v1767529804/Baklava_Latte_cttpdh.jpg",
//         price: 5.95,
//         allergens: ["Gluten", "Dairy", "Nuts"],
//       },
//     ],
//   },
//   {
//     id: 12,
//     category: "Around the World Classics",
//     slogan: "A Global Coffee Adventure in Every Sip.",
//     items: [
//       {
//         name: "Spanish Latte (Hot/Iced)",
//         price: 4.95,
//         allergens: ["Dairy"],

//         image:
//           "https://res.cloudinary.com/dhebgz7qh/image/upload/v1767529837/Spanish_Latte_l2cupo.jpg",
//       },
//       { name: "Affogato", price: 4.95, allergens: ["Dairy"] },
//       { name: "Café Shakerato", price: 4.95, allergens: ["Dairy"] },
//       {
//         name: "Dalgona",
//         price: 4.95,
//         allergens: ["Dairy"],

//         image:
//           "https://res.cloudinary.com/dhebgz7qh/image/upload/v1767529823/Dalgona_yfz9fo.jpg",
//       },
//       { name: "Turkish Coffee", price: 3.45, allergens: [] },
//       { name: "Arabic Cardamom Coffee", price: 4.95, allergens: [] },
//     ],
//   },
//   {
//     id: 14,
//     category: "Matcha Specials",
//     slogan: "Matcha Made in Heaven!",
//     items: [
//       {
//         name: "Pistachio Matcha Latte",
//         price: 4.95,
//         allergens: ["Dairy", "Nuts"],
//       },
//       {
//         name: "Mango Matcha Latte",
//         price: 4.75,
//         allergens: ["Dairy"],
//       },
//       {
//         name: "Strawberry Matcha",
//         price: 4.75,
//         allergens: ["Dairy"],
//       },
//       {
//         name: "Matcha Latte",
//         price: 4.25,
//         allergens: ["Dairy"],
//       },
//     ],
//   },
//   {
//     id: 15,
//     category: "Smoothies",
//     slogan: "Fresh, Fruity, and Full of Life!",
//     items: [
//       {
//         name: "The Green Smoothie",
//         image:
//           "https://res.cloudinary.com/dhebgz7qh/image/upload/v1767529838/The_Green_Smoothie_hkpuur.webp",
//         price: 5.45,
//         description: "Kale, Banana, Mango & Lemongrass",
//         allergens: [],
//       },
//       {
//         name: "The Red One",
//         price: 5.45,
//         description: "Açaí, Strawberry, Blueberry & Mango",
//         allergens: [],
//       },
//       {
//         name: "The Yellow One",
//         price: 5.95,
//         description: "Mango & Pear",
//         allergens: [],
//       },
//       {
//         name: "The Pink One",
//         price: 5.95,
//         description: "Strawberry & Banana",
//         allergens: [],
//       },
//       {
//         name: "The Purple One",
//         price: 5.95,
//         description: "Blueberry, Banana & Blackcurrant",
//         allergens: [],
//       },
//     ],
//   },
//   {
//     id: 16,
//     category: "Soft Drinks",
//     slogan: "Bubbles, Fizz, and Pure Refreshment!",
//     items: [
//       { name: "Cola", price: 2.75, allergens: [] },
//       { name: "Diet Cola", price: 2.75, allergens: [] },
//       { name: "Rio Tropical", price: 2.75, allergens: [] },
//       { name: "Pink Lemonade", price: 2.75, allergens: [] },
//       { name: "Small Still Water", price: 2.5, allergens: [] },
//       {
//         name: "J20 Mocks - Strawberry & Orange Mojito",
//         price: 4.95,
//         allergens: [],
//       },
//       {
//         name: "J20 Mocks - Blackberry & Blueberry Mojito",
//         price: 4.95,
//         allergens: [],
//       },
//       { name: "Red Bull", price: 4.95, allergens: [] },
//       {
//         name: "Freez - Lime and Kiwi / Strawberry Mix / Apple and Grape",
//         price: 4.95,
//         allergens: [],
//       },
//       {
//         name: "Juices - Orange, Cloudy Apple, Mango, Pineapple, Carrot",
//         price: 4.95,
//         allergens: [],
//       },
//       { name: "San Pellegrino", price: 2.95, allergens: [] },
//       { name: "Appletiser", price: 2.95, allergens: [] },
//       {
//         name: "Sparkling Lemon and Mint",
//         price: 2.95,
//         allergens: [],
//       },
//       {
//         name: "Sparkling Apple and Pear",
//         price: 2.95,
//         allergens: [],
//       },
//     ],
//   },
//   {
//     id: 17,
//     category: "Milkshakes",
//     slogan: "Shaken, Blended, and Totally Indulgent!",
//     items: [
//       {
//         name: "Chocolate / Vanilla / Strawberry",
//         price: 4.95,
//         allergens: ["Dairy"],
//       },
//       { name: "Mango Lassi", price: 5.95, allergens: ["Dairy"] },
//       {
//         name: "Baklava Pistachio",
//         price: 5.95,
//         allergens: ["Gluten", "Dairy", "Nuts"],
//       },
//       { name: "Mocha", price: 5.95, allergens: ["Dairy"] },
//     ],
//   },
//   {
//     id: 18,
//     category: "Add Ons",
//     slogan: "Your Drink, Your Way – Customize the Magic!",
//     items: [
//       { name: "Ice It", price: 0.2, allergens: [] },
//       { name: "Dirty It (Add Espresso)", price: 0.5, allergens: [] },
//       { name: "Shake It (Frappe)", price: 1.0, allergens: ["Dairy"] },
//       { name: "CBD", price: 1.0, allergens: [] },
//       { name: "Sweeten It (Syrup)", price: 0.5, allergens: [] },
//       { name: "Icecream It", price: 1.0, allergens: ["Dairy"] },
//       { name: "Bubble It", price: 0.5, allergens: [] },
//     ],
//   },
//   {
//     id: 18,
//     category: "Dessert Menu",
//     slogan:
//       "Sweet Indulgence, Perfected – Handcrafted Desserts to Savor Every Moment!",
//     displayType: "menu",
//     items: [
//       {
//         id: 1,
//         name: "Tart à la Crème Brûlée with Saffron and Vanilla",
//         price: 7.95,
//         allergens: ["Gluten", "Dairy", "Eggs"],
//       },
//       {
//         id: 2,
//         name: "Chocolate Ganache Mousse",
//         price: 6.95,
//         allergens: ["Dairy", "Eggs"],
//       },
//       {
//         id: 3,
//         name: "Red Velvet Cake",
//         image:
//           "https://res.cloudinary.com/dhebgz7qh/image/upload/v1767529841/Red_Velvet_Cake_ks8dt8.jpg",
//         price: 6.55,
//         allergens: ["Gluten", "Dairy", "Eggs"],
//       },
//       {
//         id: 4,
//         name: "Tiramisu Cake",
//         price: 6.55,
//         allergens: ["Gluten", "Dairy", "Eggs"],
//       },
//       {
//         id: 5,
//         name: "San Sebastian Cheesecake",
//         price: 6.95,
//         allergens: ["Gluten", "Dairy", "Eggs"],
//       },
//       {
//         id: 6,
//         name: "Pistachio Dream Cake",
//         price: 6.55,
//         image:
//           "https://res.cloudinary.com/dhebgz7qh/image/upload/v1767529835/Pistachio_Dream_Cake_r6ftib.webp",
//         allergens: ["Gluten", "Dairy", "Eggs", "Nuts"],
//       },
//       {
//         id: 7,
//         name: "Tres Leches (Milk Cake)",
//         price: 6.55,
//         allergens: ["Gluten", "Dairy", "Eggs"],
//       },
//       {
//         id: 8,
//         name: "Pistachio Baklava Tart",
//         price: 7.95,
//         allergens: ["Gluten", "Dairy", "Eggs", "Nuts"],
//       },
//       {
//         id: 9,
//         name: "Raspberry Tart",
//         image:
//           "https://res.cloudinary.com/dhebgz7qh/image/upload/v1767529832/Raspberry_Tart_gjjn8v.jpg",
//         price: 6.55,
//         allergens: ["Gluten", "Dairy", "Eggs"],
//       },
//       {
//         id: 10,
//         name: "Rose & Raspberry Giant Macarons",
//         price: 7.55,
//         allergens: ["Eggs", "Nuts"],
//       },
//       {
//         id: 11,
//         name: "Mini Eclairs",
//         price: 6.95,
//         allergens: ["Gluten", "Dairy", "Eggs"],
//       },
//       {
//         id: 12,
//         name: "Bowl of Ice Cream (Vanilla, Chocolate, Strawberry)",
//         price: 4.95,
//         allergens: ["Dairy"],
//       },
//     ],
//   },
// ];

// export const desertMenu = [
//   {
//     id: 1,
//     name: "Tart à la Crème Brûlée with Saffron and Vanilla",
//     price: 7.95,
//   },
//   {
//     id: 2,
//     name: "Chocolate Ganache Mousse",
//     price: 6.95,
//   },
//   {
//     id: 3,
//     name: "Red Velvet Cake",
//     price: 6.55,
//   },
//   {
//     id: 4,
//     name: "Tiramisu Cake",
//     price: 6.55,
//   },
//   {
//     id: 5,
//     name: "San Sebastian Cheesecake",
//     price: 6.95,
//   },
//   {
//     id: 6,
//     name: "Pistachio Dream Cake",
//     price: 6.55,
//   },
//   {
//     id: 7,
//     name: "Tres Leches (Milk Cake)",
//     price: 6.55,
//   },
//   {
//     id: 8,
//     name: "Pistachio Baklava Tart",
//     price: 7.95,
//   },
//   {
//     id: 9,
//     name: "Raspberry Tart",
//     price: 6.55,
//   },
//   {
//     id: 10,
//     name: "Rose & Raspberry Giant Macarons",
//     price: 7.55,
//   },
//   {
//     id: 11,
//     name: "Mini Eclairs",
//     price: 6.95,
//   },
//   {
//     id: 12,
//     name: "Bowl of Ice Cream (Vanilla, Chocolate, Strawberry)",
//     price: 4.95,
//   },
// ];



export const menu_1 = [
  {
    id: 1,
    category: "Breakfast Croissant",
    slogan: "Flaky, Buttery, Irresistible – A Bite of Paris in Every Layer!",
    image:
      "https://res.cloudinary.com/dhebgz7qh/image/upload/v1767529826/Jambon-Fromage_Croissant_tv5cmy.jpg",
    items: [
      {
        name: "Jambon-Fromage Croissant",
        price: 9.55,
        description:
          "Croissant filled with turkey ham, Dijon mustard, and Swiss cheese.",
        allergens: ["Gluten", "Dairy", "Eggs", "Mustard"],
        allergensItems: {
          Celery: false,
          "Cereals/Gluten": true,
          Crustaceans: false,
          Eggs: true,
          Fish: false,
          Lupin: false,
          Milk: true,
          Mustard: true,
          Nuts: false,
          Peanuts: false,
          "Sesame Seeds": false,
          Soya: false,
          "Sulphur Dioxide": false,
        },
      },
      {
        name: "Scrambled Egg and Bacon Croissant",
        price: 10.55,
        description:
          "Croissant, scrambled eggs, crispy bacon, and cheddar cheese.",
        allergens: ["Gluten", "Dairy", "Eggs"],
        allergensItems: {
          Celery: false,
          "Cereals/Gluten": true,
          Crustaceans: false,
          Eggs: true,
          Fish: false,
          Lupin: false,
          Milk: true,
          Mustard: false,
          Nuts: false,
          Peanuts: false,
          "Sesame Seeds": false,
          Soya: false,
          "Sulphur Dioxide": false,
        },
      },
      {
        name: "Smoked Salmon Croissant",
        image:
          "https://res.cloudinary.com/dhebgz7qh/image/upload/v1767529845/Smoked_Salmon_Croissant_fpncmv.jpg",
        price: 12.55,
        description:
          "Croissant, smoked salmon, cream cheese, capers, red onion, and rocket.",
        allergens: ["Gluten", "Dairy", "Fish"],
        allergensItems: {
          Celery: false,
          "Cereals/Gluten": true,
          Crustaceans: false,
          Eggs: true,
          Fish: true,
          Lupin: false,
          Milk: true,
          Mustard: false,
          Nuts: false,
          Peanuts: false,
          "Sesame Seeds": false,
          Soya: false,
          "Sulphur Dioxide": false,
        },
      },
      {
        name: "Avocado and Egg Croissant",
        price: 10.55,
        description:
          "Croissant, avocado, sunny-side up egg, tomatoes, and Harissa mayo.",
        allergens: ["Gluten", "Dairy", "Eggs"],
        allergensItems: {
          Celery: false,
          "Cereals/Gluten": true,
          Crustaceans: false,
          Eggs: true,
          Fish: false,
          Lupin: false,
          Milk: true,
          Mustard: false,
          Nuts: false,
          Peanuts: false,
          "Sesame Seeds": false,
          Soya: false,
          "Sulphur Dioxide": false,
        },
      },
      {
        name: "Croissant Addict Special",
        price: 13.55,
        description:
          "Seared croissant, poached eggs, smashed avocado, rocket, and parmesan cheese.",
        allergens: ["Gluten", "Dairy", "Eggs"],
        allergensItems: {
          Celery: false,
          "Cereals/Gluten": true,
          Crustaceans: false,
          Eggs: true,
          Fish: false,
          Lupin: false,
          Milk: true,
          Mustard: false,
          Nuts: false,
          Peanuts: false,
          "Sesame Seeds": false,
          Soya: false,
          "Sulphur Dioxide": false,
        },
      },
      {
        name: " Butter Croissant",
        price: 1.95,
        description: "Butter croissant.",
        allergensItems: {
          Celery: false,
          "Cereals/Gluten": true,
          Crustaceans: false,
          Eggs: true,
          Fish: false,
          Lupin: false,
          Milk: true,
          Mustard: false,
          Nuts: false,
          Peanuts: false,
          "Sesame Seeds": false,
          Soya: false,
          "Sulphur Dioxide": false,
        },
      },
      {
        name: "Croissant Chocolate",
        price: 1.95,
        description: "",
        allergensItems: {
          Celery: false,
          "Cereals/Gluten": true,
          Crustaceans: false,
          Eggs: true,
          Fish: false,
          Lupin: false,
          Milk: true,
          Mustard: false,
          Nuts: true,
          Peanuts: false,
          "Sesame Seeds": false,
          Soya: false,
          "Sulphur Dioxide": false,
        },
      },
      {
        name: "Croissant Pistachio ",
        image:
          "https://res.cloudinary.com/dhebgz7qh/image/upload/v1767529834/Croissant_Pistachio_itmaea.jpg",
        price: 5.95,
        description: "",
        allergens: ["Gluten", "Dairy", "Eggs", "Tree Nuts"],
        allergensItems: {
          Celery: false,
          "Cereals/Gluten": true,
          Crustaceans: false,
          Eggs: true,
          Fish: false,
          Lupin: false,
          Milk: true,
          Mustard: false,
          Nuts: true,
          Peanuts: false,
          "Sesame Seeds": false,
          Soya: false,
          "Sulphur Dioxide": false,
        },
      },
      {
        name: "Croissant Almond ",
        image:
          "https://res.cloudinary.com/dhebgz7qh/image/upload/v1767529834/Croissant_Pistachio_itmaea.jpg",
        price: 3.95,
        description: "",
        allergensItems: {
          Celery: false,
          "Cereals/Gluten": true,
          Crustaceans: false,
          Eggs: true,
          Fish: false,
          Lupin: false,
          Milk: true,
          Mustard: false,
          Nuts: true,
          Peanuts: false,
          "Sesame Seeds": false,
          Soya: false,
          "Sulphur Dioxide": false,
        },
      },
    ],
  },
  {
    id: 2,
    category: "Toasts and Rolls",
    slogan: "Golden, Toasted, and Stuffed with Love!",
    image:
      "https://res.cloudinary.com/dhebgz7qh/image/upload/v1767529840/Toasts_and_Rolls_u6inky.jpg",
    items: [
      {
        name: "Truffle & Cheese Egg Rolls",
        price: 10.55,
        description:
          "Soft and flaky rolls filled with creamy scrambled eggs, melted cheese, and a hint of truffle oil, topped with parmesan rocket.",
        allergens: ["Gluten", "Dairy", "Eggs"],
        allergensItems: {
          Celery: false,
          "Cereals/Gluten": true,
          Crustaceans: false,
          Eggs: true,
          Fish: false,
          Lupin: false,
          Milk: true,
          Mustard: false,
          Nuts: false,
          Peanuts: false,
          "Sesame Seeds": false,
          Soya: false,
          "Sulphur Dioxide": false,
        },
      },
      {
        name: "Middle Eastern Roll",
        price: 9.95,
        description:
          "Soft and flaky rolls filled with falafel, fresh vegetables, hummus, and drizzled with tahini sauce and sumac.",
        allergens: ["Gluten", "Sesame"],
        allergensItems: {
          Celery: false,
          "Cereals/Gluten": true,
          Crustaceans: false,
          Eggs: false,
          Fish: false,
          Lupin: false,
          Milk: false,
          Mustard: false,
          Nuts: false,
          Peanuts: false,
          "Sesame Seeds": false,
          Soya: false,
          "Sulphur Dioxide": false,
        },
      },
      {
        name: "Lahma Brioche",
        price: 13.75,
        image:
          "https://res.cloudinary.com/dhebgz7qh/image/upload/v1767529832/Lahma_Brioche_tayxif.webp",
        description:
          "Shredded smoked brisket, generously filled on a soft, buttery brioche toast, topped with crispy fried shallots and a touch of Harissa mayo.",
        allergens: ["Gluten", "Dairy", "Eggs"],
        allergensItems: {
          Celery: false,
          "Cereals/Gluten": true,
          Crustaceans: false,
          Eggs: true,
          Fish: false,
          Lupin: false,
          Milk: true,
          Mustard: false,
          Nuts: false,
          Peanuts: false,
          "Sesame Seeds": false,
          Soya: false,
          "Sulphur Dioxide": false,
        },
      },
      {
        name: "Loaded Toast",
        price: 12.95,
        image:
          "https://res.cloudinary.com/dhebgz7qh/image/upload/v1767529834/Loaded_Toast_nonqq8.webp",
        description:
          "Brioche toast filled with crispy hash browns, beef sausage, and beef bacon, drizzled with Harissa mayo, and garnished with fresh herbs.",
        allergens: ["Gluten", "Dairy", "Eggs"],
        allergensItems: {
          Celery: false,
          "Cereals/Gluten": true,
          Crustaceans: false,
          Eggs: true,
          Fish: false,
          Lupin: false,
          Milk: true,
          Mustard: false,
          Nuts: false,
          Peanuts: false,
          "Sesame Seeds": false,
          Soya: false,
          "Sulphur Dioxide": false,
        },
      },
    ],
  },
  {
    id: 3,
    category: "Classic Breakfast",
    slogan: "Timeless Mornings, One Bite at a Time!",
    image:
      "https://res.cloudinary.com/dhebgz7qh/image/upload/v1767529834/Croissant_Pistachio_itmaea.jpg",
    items: [
      {
        name: "Full English",
        price: 13.95,
        description:
          "Fried eggs, beef sausages, crispy beef bacon, baked beans, grilled tomatoes, sautéed mushrooms, golden hash browns, and toast.",
        allergens: ["Gluten", "Eggs"],
        allergensItems: {
          Celery: false,
          "Cereals/Gluten": true,
          Crustaceans: false,
          Eggs: true,
          Fish: false,
          Lupin: false,
          Milk: true,
          Mustard: false,
          Nuts: false,
          Peanuts: false,
          "Sesame Seeds": false,
          Soya: false,
          "Sulphur Dioxide": false,
        },
      },
      {
        name: "SpudBowl",
        price: 12.95,
        description:
          "A bowl of crispy hash browns topped with poached eggs, smashed avocado, pickled onions, a drizzle of harissa mayo.",
        allergens: ["Eggs", "Dairy"],
        allergensItems: {
          Celery: false,
          "Cereals/Gluten": false,
          Crustaceans: false,
          Eggs: true,
          Fish: false,
          Lupin: false,
          Milk: false,
          Mustard: false,
          Nuts: false,
          Peanuts: false,
          "Sesame Seeds": false,
          Soya: false,
          "Sulphur Dioxide": false,
        },
      },
      {
        name: "Turkish Breakfast",
        price: 14.95,
        image:
          "https://res.cloudinary.com/dhebgz7qh/image/upload/v1767529845/Turkish_Breakfast_yrrguc.webp",
        description:
          "A vibrant selection of boiled eggs, feta cheese, olives, spicy sausage, tomatoes, cucumbers, honey butter, jam, and simit.",
        allergens: ["Gluten", "Dairy", "Eggs", "Nuts"],
        allergensItems: {
          Celery: false,
          "Cereals/Gluten": true,
          Crustaceans: false,
          Eggs: true,
          Fish: false,
          Lupin: false,
          Milk: true,
          Mustard: false,
          Nuts: false,
          Peanuts: false,
          "Sesame Seeds": false,
          Soya: false,
          "Sulphur Dioxide": false,
        },
      },
      {
        name: "Middle Eastern Feast",
        price: 15.95,
        description:
          "An array of Middle Eastern delights, including: baba ghanoush, fried boiled eggs, falafel, foul masri, chips, mix pickles, pita bread.",
        allergens: ["Gluten", "Eggs", "Dairy", "Sesame"],
        allergensItems: {
          Celery: false,
          "Cereals/Gluten": true,
          Crustaceans: false,
          Eggs: true,
          Fish: false,
          Lupin: false,
          Milk: false,
          Mustard: false,
          Nuts: false,
          Peanuts: false,
          "Sesame Seeds": true,
          Soya: false,
          "Sulphur Dioxide": false,
        },
      },
      {
        name: "Classic Shakshuka",
        image:
          "https://res.cloudinary.com/dhebgz7qh/image/upload/v1767529819/Classic_Shakshuka_zntz65.jpg ",
        price: 13.95,
        description:
          "Runny eggs in a rich tomato, pepper, and onion sauce, served with sourdough.",
        allergens: ["Eggs", "Dairy", "Gluten"],
        allergensItems: {
          Celery: false,
          "Cereals/Gluten": false,
          Crustaceans: false,
          Eggs: true,
          Fish: false,
          Lupin: false,
          Milk: true,
          Mustard: false,
          Nuts: false,
          Peanuts: false,
          "Sesame Seeds": false,
          Soya: false,
          "Sulphur Dioxide": false,
        },
      },
      {
        name: "Pancake à la canadienne",
        price: 15.95,
        description:
          "Fluffy pancakes, beef sausage, beef bacon, scrambled eggs topped with maple and fresh berries.",
        allergens: ["Gluten", "Dairy", "Eggs"],
        allergensItems: {
          Celery: false,
          "Cereals/Gluten": true,
          Crustaceans: false,
          Eggs: true,
          Fish: false,
          Lupin: false,
          Milk: true,
          Mustard: false,
          Nuts: false,
          Peanuts: false,
          "Sesame Seeds": false,
          Soya: false,
          "Sulphur Dioxide": false,
        },
      },
    ],
  },
  {
    id: 4,
    category: "Artisan Benedict",
    slogan: "Eggsquisite Delights with a Gourmet Twist!",
    image:
      "https://res.cloudinary.com/dhebgz7qh/image/upload/v1767529804/Artisan_Benedict_tlnupg.jpg",
    items: [
      {
        name: "Avo Tartine",
        price: 11.95,
        description:
          "Smashed avocado, sliced radish, a drizzle of lemon vinaigrette, sprinkled with black seeds on a sourdough.",
        allergens: ["Gluten", "Sesame"],
        allergensItems: {
          Celery: false,
          "Cereals/Gluten": true,
          Crustaceans: false,
          Eggs: false,
          Fish: false,
          Lupin: false,
          Milk: false,
          Mustard: false,
          Nuts: false,
          Peanuts: false,
          "Sesame Seeds": true,
          Soya: false,
          "Sulphur Dioxide": false,
        },
      },
      {
        name: "Eggs Benedict",
        price: 12.55,
        description:
          "Classic poached eggs, beef bacon, and Harissa hollandaise on an English muffin.",
        allergens: ["Gluten", "Eggs", "Dairy"],
        allergensItems: {
          Celery: false,
          "Cereals/Gluten": true,
          Crustaceans: false,
          Eggs: true,
          Fish: false,
          Lupin: false,
          Milk: true,
          Mustard: false,
          Nuts: false,
          Peanuts: false,
          "Sesame Seeds": false,
          Soya: false,
          "Sulphur Dioxide": false,
        },
      },
      {
        name: "Egg Royale",
        image:
          "https://res.cloudinary.com/dhebgz7qh/image/upload/v1767529825/Egg_Royale_whb5vh.jpg",
        price: 13.55,
        description:
          "Poached eggs, smoked salmon, and Harissa hollandaise on an English muffin.",
        allergens: ["Gluten", "Eggs", "Dairy", "Fish"],
        allergensItems: {
          Celery: false,
          "Cereals/Gluten": true,
          Crustaceans: false,
          Eggs: true,
          Fish: false,
          Lupin: false,
          Milk: true,
          Mustard: false,
          Nuts: false,
          Peanuts: false,
          "Sesame Seeds": false,
          Soya: false,
          "Sulphur Dioxide": false,
        },
      },
      {
        name: "Baba Ganoush Benedict",
        price: 13.95,
        description:
          "Poached eggs, smoked aubergine puree, pickled beetroot, and Harissa hollandaise on a sourdough, sprinkled with sumac.",
        allergens: ["Gluten", "Eggs", "Dairy"],
        allergensItems: {
          Celery: false,
          "Cereals/Gluten": true,
          Crustaceans: false,
          Eggs: true,
          Fish: false,
          Lupin: false,
          Milk: true,
          Mustard: false,
          Nuts: false,
          Peanuts: false,
          "Sesame Seeds": true,
          Soya: false,
          "Sulphur Dioxide": false,
        },
      },
      {
        name: "Goatacado",
        price: 14.95,
        description:
          "Poached eggs, creamy goat cheese, avocado, and pickled onions with Harissa hollandaise on a sourdough.",
        allergens: ["Gluten", "Eggs", "Dairy", "Nuts"],
        allergensItems: {
          Celery: false,
          "Cereals/Gluten": true,
          Crustaceans: false,
          Eggs: true,
          Fish: false,
          Lupin: false,
          Milk: true,
          Mustard: false,
          Nuts: false,
          Peanuts: false,
          "Sesame Seeds": false,
          Soya: false,
          "Sulphur Dioxide": false,
        },
      },
      {
        name: "Truffle Mushroom Benedict",
        price: 13.95,
        description:
          "Caramelized onions, truffle-infused portobello mushroom, and cashew hollandaise on a sourdough.",
        allergens: ["Gluten", "Eggs", "Dairy"],
        allergensItems: {
          Celery: false,
          "Cereals/Gluten": true,
          Crustaceans: false,
          Eggs: false,
          Fish: false,
          Lupin: false,
          Milk: false,
          Mustard: false,
          Nuts: false,
          Peanuts: false,
          "Sesame Seeds": false,
          Soya: false,
          "Sulphur Dioxide": false,
        },
      },
    ],
  },
  {
    id: 5,
    category: "Signature Breakfast",
    image:
      "https://res.cloudinary.com/dhebgz7qh/image/upload/v1767529848/Waffle_Truffle_ako4il.jpg",
    slogan: "Bold Flavors, Signature Perfection!",
    items: [
      {
        name: "Waffle Truffle",
        price: 14.95,
        image:
          "https://res.cloudinary.com/dhebgz7qh/image/upload/v1767529848/Waffle_Truffle_ako4il.jpg",
        description:
          "Waffles topped with brie cheese, figs, honey on a bed of sweet carrot purée, and a drizzle of truffle oil.",
        allergens: ["Gluten", "Dairy", "Eggs"],
        allergensItems: {
          Celery: false,
          "Cereals/Gluten": true,
          Crustaceans: false,
          Eggs: true,
          Fish: false,
          Lupin: false,
          Milk: true,
          Mustard: false,
          Nuts: false,
          Peanuts: false,
          "Sesame Seeds": false,
          Soya: false,
          "Sulphur Dioxide": false,
        },
      },
      {
        name: "Croque Monsieur",
        image:
          "https://res.cloudinary.com/dhebgz7qh/image/upload/v1767529830/Croque_Monsieur_c2ptgy.jpg",
        price: 15.95,
        description:
          "Toasted baked sourdough layered with turkey ham, creamy béchamel sauce, and melted Swiss cheese served with mix leaves.",
        allergens: ["Gluten", "Dairy", "Eggs"],
        allergensItems: {
          Celery: false,
          "Cereals/Gluten": true,
          Crustaceans: false,
          Eggs: false,
          Fish: false,
          Lupin: false,
          Milk: true,
          Mustard: false,
          Nuts: false,
          Peanuts: false,
          "Sesame Seeds": false,
          Soya: false,
          "Sulphur Dioxide": false,
        },
      },
      {
        name: "French Toast",
        image:
          "https://res.cloudinary.com/dhebgz7qh/image/upload/v1767529828/French_Toast_h6n9lx.jpg",
        price: 15.95,
        description:
          "Thick slices of brioche soaked in a cinnamon-vanilla-egg batter, served with berries.",
        allergens: ["Gluten", "Dairy", "Eggs"],
        allergensItems: {
          Celery: false,
          "Cereals/Gluten": true,
          Crustaceans: false,
          Eggs: true,
          Fish: false,
          Lupin: false,
          Milk: true,
          Mustard: false,
          Nuts: true,
          Peanuts: false,
          "Sesame Seeds": false,
          Soya: false,
          "Sulphur Dioxide": false,
        },
      },
      {
        name: "Bacon Egg Brioche",
        price: 12.95,
        description:
          "A soft brioche bed topped with crispy bacon, scrambled eggs, and a hint of cheddar cheese served with crispy leaves.",
        allergens: ["Gluten", "Dairy", "Eggs"],
        allergensItems: {
          Celery: false,
          "Cereals/Gluten": true,
          Crustaceans: false,
          Eggs: true,
          Fish: false,
          Lupin: false,
          Milk: true,
          Mustard: false,
          Nuts: false,
          Peanuts: false,
          "Sesame Seeds": false,
          Soya: false,
          "Sulphur Dioxide": false,
        },
      },
      {
        name: "Nour’s Special Breakfast",
        price: 15.95,
        description:
          "Crispy Turkish simit bread layered with sliced avocado and cream cheese, pureed chickpeas, and crushed walnuts, and a scattering of fresh seasonal fruit.",
        allergens: ["Gluten", "Dairy", "Eggs", "Nuts"],
        allergensItems: {
          Celery: false,
          "Cereals/Gluten": true,
          Crustaceans: false,
          Eggs: false,
          Fish: false,
          Lupin: false,
          Milk: true,
          Mustard: false,
          Nuts: false,
          Peanuts: false,
          "Sesame Seeds": true,
          Soya: false,
          "Sulphur Dioxide": false,
        },
      },
      {
        name: "Foul Masri",
        price: 11.95,
        description:
          "A classic Egyptian dish made with slow-cooked fava beans, seasoned with garlic, cumin, lemon juice, and olive oil. Served with warm pita bread and garnished with fresh herbs, diced tomatoes, and a drizzle of tahini.",
        allergens: ["Gluten", "Dairy", "Eggs", "Nuts"],
        allergensItems: {
          Celery: false,
          "Cereals/Gluten": false,
          Crustaceans: false,
          Eggs: false,
          Fish: false,
          Lupin: false,
          Milk: true,
          Mustard: false,
          Nuts: false,
          Peanuts: false,
          "Sesame Seeds": false,
          Soya: false,
          "Sulphur Dioxide": false,
        },
      },
      {
        name: "Eggah Omelette",
        price: 13.55,
        description:
          "A fluffy omelette with fresh herbs, spring onions, sautéed potato, and a hint of cumin. Topped with brie cheese.",
        allergens: ["Gluten", "Dairy", "Eggs", "Nuts"],
        allergensItems: {
          Celery: false,
          "Cereals/Gluten": false,
          Crustaceans: false,
          Eggs: true,
          Fish: false,
          Lupin: false,
          Milk: true,
          Mustard: false,
          Nuts: false,
          Peanuts: false,
          "Sesame Seeds": false,
          Soya: false,
          "Sulphur Dioxide": false,
        },
      },
    ],
  },
  {
    category: "All-Day Brunch",
    slogan: "Brunch O’Clock, Anytime You Crave",
    image:
      "https://res.cloudinary.com/dhebgz7qh/image/upload/v1767529834/Salads_krgtsh.jpg",
    items: [
      {
        name: "Chicken Escalope",
        price: 15.95,
        description:
          "Crispy, golden-breaded chicken breast served with creamy Parmesan sauce, mixed greens, and French fries.",
        allergens: ["Gluten", "Dairy"],
         allergensItems: {
          Celery: false,
          "Cereals/Gluten": true,
          Crustaceans: false,
          Eggs: true,
          Fish: false,
          Lupin: false,
          Milk: true,
          Mustard: false,
          Nuts: false,
          Peanuts: false,
          "Sesame Seeds": false,
          Soya: false,
          "Sulphur Dioxide": false,
        },
      },
      {
        name: "Cheezy Split Burger (Smashed beef)",
        price: 15.95,
        description:
          "A burger cut in half served on a sizzling skillet on top a pool of rich, melted cheese sauce with French fries.",
        allergens: ["Gluten", "Dairy"],
         allergensItems: {
          Celery: false,
          "Cereals/Gluten": true,
          Crustaceans: false,
          Eggs: false,
          Fish: false,
          Lupin: false,
          Milk: true,
          Mustard: false,
          Nuts: false,
          Peanuts: false,
          "Sesame Seeds": false,
          Soya: false,
          "Sulphur Dioxide": false,
        },
      },
      {
        name: "Cheezy Split Burger (Chicken)",
        price: 14.95,
        description:
          "Grilled chicken breast wrapped in a soft flatbread with sautéed mixed veg and algerienne sauce with French fries.",
        allergens: ["Gluten", "Dairy"],
         allergensItems: {
          Celery: false,
          "Cereals/Gluten": true,
          Crustaceans: false,
          Eggs: false,
          Fish: false,
          Lupin: false,
          Milk: true,
          Mustard: false,
          Nuts: false,
          Peanuts: false,
          "Sesame Seeds": false,
          Soya: false,
          "Sulphur Dioxide": false,
        },
      },
      {
        name: "Poulet Wrap",
        price: 15.55,
        description:
          "A burger cut in half served on a sizzling skillet on top a pool of rich, melted cheese sauce with French fries.",
        allergens: ["Gluten", "Dairy"],
         allergensItems: {
          Celery: false,
          "Cereals/Gluten": true,
          Crustaceans: false,
          Eggs: false,
          Fish: false,
          Lupin: false,
          Milk: true,
          Mustard: false,
          Nuts: false,
          Peanuts: false,
          "Sesame Seeds": false,
          Soya: false,
          "Sulphur Dioxide": false,
        },
      },
      {
        name: "Fish and Chips",
        price: 14.55,
        description:
          "Crispy, golden-battered cod served with perfectly seasoned chips and a side of tangy tartar sauce.",
        allergens: ["Gluten", "Dairy"],
         allergensItems: {
          Celery: false,
          "Cereals/Gluten": true,
          Crustaceans: false,
          Eggs: false,
          Fish: false,
          Lupin: false,
          Milk: false,
          Mustard: false,
          Nuts: false,
          Peanuts: false,
          "Sesame Seeds": false,
          Soya: false,
          "Sulphur Dioxide": false,
        },
      },
      {
        name: "Nour’s Burger",
        price: 16.95,
        description:
          "Tender pulled beef slow-cooked in a blend of spices, piled high on a toasted brioche bun. Topped with melted cheese, pickled onions, served with French fries.",
        allergens: ["Gluten", "Dairy"],
         allergensItems: {
          Celery: false,
          "Cereals/Gluten": true,
          Crustaceans: false,
          Eggs: true,
          Fish: false,
          Lupin: false,
          Milk: true,
          Mustard: false,
          Nuts: false,
          Peanuts: false,
          "Sesame Seeds": false,
          Soya: false,
          "Sulphur Dioxide": false,
        },
      },
      {
        name: "Zaatar Pita Nachos",
        price: 15.55,
        description:
          "Crispy pita chips dusted with zaatar spice, topped with grilled chicken, fresh herbs, tangy cheese sauce, pickled onions, and a drizzle of algerienne sauce.",
        allergens: ["Gluten", "Dairy"],
         allergensItems: {
          Celery: false,
          "Cereals/Gluten": true,
          Crustaceans: false,
          Eggs: true,
          Fish: false,
          Lupin: false,
          Milk: true,
          Mustard: false,
          Nuts: false,
          Peanuts: false,
          "Sesame Seeds": false,
          Soya: false,
          "Sulphur Dioxide": false,
        },
      },
    ],
  },
  {
    id: 1001,
    category: "CHEF SPECIAL",
    slogan: "Crafted by the Chef, Served with Soul.",
    image:
      "https://res.cloudinary.com/dhebgz7qh/image/upload/v1767529838/The_Green_Smoothie_hkpuur.webp",
    items: [
      {
        name: "Chicken Olive Tagine",
        price: 22.95,
        description:
          "Slow-cooked chicken with green olives, preserved lemons, and Moroccan spices, served with fluffy couscous. A burst of North African flavor!",
        allergens: ["Gluten"],
        allergensItems: {
          Celery: false,
          "Cereals/Gluten": true,
          Crustaceans: false,
          Eggs: false,
          Fish: false,
          Lupin: false,
          Milk: false,
          Mustard: false,
          Nuts: false,
          Peanuts: false,
          "Sesame Seeds": false,
          Soya: false,
          "Sulphur Dioxide": false,
        },
      },
      {
        name: "Barkouk Lamb Tagine",
        price: 24.95,
        description:
          "Tender lamb slow-cooked with apricots, prunes, and warm spices saffron rice. Sweet meets savory perfection!",
        allergens: [],
        allergensItems: {
          Celery: false,
          "Cereals/Gluten": false,
          Crustaceans: false,
          Eggs: false,
          Fish: false,
          Lupin: false,
          Milk: false,
          Mustard: false,
          Nuts: false,
          Peanuts: false,
          "Sesame Seeds": false,
          Soya: false,
          "Sulphur Dioxide": false,
        },
      },
      {
        name: "Beef Meatball Tagine",
        price: 19.95,
        description:
          "Juicy spiced beef meatballs in a rich tomato sauce, topped with an egg and served with crusty bread for dipping. Comfort food with a kick!",
        allergens: ["Gluten", "Eggs"],
        allergensItems: {
          Celery: false,
          "Cereals/Gluten": true,
          Crustaceans: false,
          Eggs: true,
          Fish: false,
          Lupin: false,
          Milk: false,
          Mustard: false,
          Nuts: false,
          Peanuts: false,
          "Sesame Seeds": false,
          Soya: false,
          "Sulphur Dioxide": false,
        },
      },
      {
        name: "Chicken Pastilla",
        price: 18.95,
        description:
          "Flaky pastry stuffed with spiced chicken, almonds, and a touch of cinnamon, topped with a hint of caster sugar. A sweet and savory pie delight!",
        allergens: ["Gluten", "Nuts"],
        allergensItems: {
          Celery: false,
          "Cereals/Gluten": true,
          Crustaceans: false,
          Eggs: false,
          Fish: false,
          Lupin: false,
          Milk: false,
          Mustard: false,
          Nuts: true,
          Peanuts: false,
          "Sesame Seeds": false,
          Soya: false,
          "Sulphur Dioxide": false,
        },
      },
    ],
  },
  {
    id: 6,
    category: "Salads",
    slogan: "Fresh, Crisp, and Full of Vibrant Goodness!",
    image:
      "https://res.cloudinary.com/dhebgz7qh/image/upload/v1767529834/Salads_krgtsh.jpg",
    items: [
      {
        name: "Herb Feta and Olive Tabbouleh",
        price: 11.55,
        description:
          "Fresh herbs, feta cheese, olives, and bulgur wheat, with a lemon dressing.",
        allergens: ["Gluten", "Dairy"],
      },
            {
        name: "nicoise fattoush salad",
        price: 11.55,
        description:
          "A refreshing blend of crispy pita chips, olives, cherry tomatoes, fresh herbs, and boiled eggs, all tossed in a simple lemon-sumac vinaigrette.",
        // allergens: ["Gluten", "Dairy"],
      },
                  {
        name: "Wedge Avocado Salad with Parmesan",
        price: 11.95,
        description:
          "Crisp lettuce wedges topped with sliced avocado, Parmesan and fresh herbs, drizzled with a light lemon vinaigrette and Harissa mayo.",
        // allergens: ["Gluten", "Dairy"],
      },
      {
        name: "Avocado Salad with Sumac",
        price: 10.95,
        description:
          "Crispy mixed lettuce, sliced avocado, pomegranate, crushed walnuts, and Harissa mayo.",
        allergens: ["Dairy", "Nuts"],
      },
    ],
  },
  {
    id: 7,
    category: "Coffee",
    slogan: "Brewed to Perfection, Sipped with Passion.",
    image:
      "https://res.cloudinary.com/dhebgz7qh/image/upload/v1767529819/Coffee_y1u5ai.jpg",
    items: [
      { name: "Double Espresso", price: 2.65, allergens: [] },
      { name: "Americano", price: 2.65, allergens: [] },
      { name: "Macchiato", price: 2.75, allergens: ["Dairy"] },
      { name: "Cortado", price: 3.45, allergens: ["Dairy"] },
      { name: "Flat White", price: 3.45, allergens: ["Dairy"] },
      { name: "Cappuccino", price: 3.65, allergens: ["Dairy"] },
      {
        name: "Latte",
        image:
          "https://res.cloudinary.com/dhebgz7qh/image/upload/v1767529831/Latte_c9jqf9.jpg",
        price: 3.75,
        allergens: ["Dairy"],
      },
      { name: "Mocha", price: 3.85, allergens: ["Dairy"] },
    ],
  },
  {
    id: 8,
    category: "Filter Coffee",
    slogan: "Pure, Slow, and Worth the Wait.",
    items: [
      { name: "V60 for One", price: 4.95, allergens: [] },
      { name: "V60 for Share", price: 6.95, allergens: [] },
    ],
  },
  {
    id: 9,
    category: "Not Coffee",
    slogan: "Beyond Coffee, Beyond Ordinary.",
    items: [
      {
        name: "Pot of Tea (English Breakfast / Earl Grey)",
        price: 3.45,
        allergens: [],
      },
      { name: "Decaf Tea", price: 2.95, allergens: [] },
      { name: "Green Tea", price: 2.45, allergens: [] },
      { name: "Chamomile Tea", price: 2.65, allergens: [] },
      { name: "Peppermint Tea", price: 2.65, allergens: [] },
      { name: "Berry Tea", price: 3.35, allergens: [] },
      { name: "Chai Latte", price: 3.65, allergens: ["Dairy"] },
      { name: "Hot Chocolate", price: 3.85, allergens: ["Dairy"] },
    ],
  },
  {
    id: 10,
    category: "Bubble Tea",
    slogan: "Sip, Pop, and Enjoy the Fun!",
    items: [
      {
        name: "Pick Your Base - Watermelon, Strawberry & Raspberry, Peach & Passion",
        price: 3.5,
        allergens: [],
      },
      {
        name: "Pick Your Bubbles - Mango, Passionfruit, Strawberry (per scoop)",
        price: 0.5,
        allergens: [],
      },
    ],
  },
  {
    id: 11,
    category: "Nour's Specialty Coffees",
    slogan: "Where Tradition Meets a Twist of Magic.",
    items: [
      {
        name: "Tiramisu Latte",
        price: 6.55,
        allergens: ["Gluten", "Dairy", "Eggs"],
      },
      {
        name: "Blue Moon Latte (Hot/Iced)",
        price: 6.55,
        allergens: ["Dairy"],
        image:
          "https://res.cloudinary.com/dhebgz7qh/image/upload/v1767529835/Blue_Moon_Latte_katty1.webp",
      },
      {
        name: "Crème Brûlée Latte (Hot/Iced)",
        price: 6.55,
        allergens: ["Dairy", "Eggs"],
      },
      {
        name: "Pistachio and Rose Latte (Hot/Iced)",
        price: 5.95,
        allergens: ["Dairy", "Nuts"],
      },
      {
        name: "Croissant Latte",
        price: 5.95,
        allergens: ["Gluten", "Dairy", "Eggs"],
      },
      {
        name: "Halva Latte",
        price: 5.95,
        allergens: ["Dairy", "Sesame"],
      },
      {
        name: "Baklava Latte",
        image:
          "https://res.cloudinary.com/dhebgz7qh/image/upload/v1767529804/Baklava_Latte_cttpdh.jpg",
        price: 5.95,
        allergens: ["Gluten", "Dairy", "Nuts"],
      },
    ],
  },
  {
    id: 12,
    category: "Around the World Classics",
    slogan: "A Global Coffee Adventure in Every Sip.",
    items: [
      {
        name: "Spanish Latte (Hot/Iced)",
        price: 4.95,
        allergens: ["Dairy"],

        image:
          "https://res.cloudinary.com/dhebgz7qh/image/upload/v1767529837/Spanish_Latte_l2cupo.jpg",
      },
      { name: "Affogato", price: 4.95, allergens: ["Dairy"] },
      { name: "Café Shakerato", price: 4.95, allergens: ["Dairy"] },
      {
        name: "Dalgona",
        price: 4.95,
        allergens: ["Dairy"],

        image:
          "https://res.cloudinary.com/dhebgz7qh/image/upload/v1767529823/Dalgona_yfz9fo.jpg",
      },
      { name: "Turkish Coffee", price: 3.45, allergens: [] },
      { name: "Arabic Cardamom Coffee", price: 4.95, allergens: [] },
    ],
  },
  {
    id: 14,
    category: "Matcha Specials",
    slogan: "Matcha Made in Heaven!",
    items: [
      {
        name: "Pistachio Matcha Latte",
        price: 4.95,
        allergens: ["Dairy", "Nuts"],
      },
      {
        name: "Mango Matcha Latte",
        price: 4.75,
        allergens: ["Dairy"],
      },
      {
        name: "Strawberry Matcha",
        price: 4.75,
        allergens: ["Dairy"],
      },
      {
        name: "Matcha Latte",
        price: 4.25,
        allergens: ["Dairy"],
      },
    ],
  },
  {
    id: 15,
    category: "Smoothies",
    slogan: "Fresh, Fruity, and Full of Life!",
    items: [
      {
        name: "The Green Smoothie",
        image:
          "https://res.cloudinary.com/dhebgz7qh/image/upload/v1767529838/The_Green_Smoothie_hkpuur.webp",
        price: 5.45,
        description: "Kale, Banana, Mango & Lemongrass",
        allergens: [],
      },
      {
        name: "The Red One",
        price: 5.45,
        description: "Açaí, Strawberry, Blueberry & Mango",
        allergens: [],
      },
      {
        name: "The Yellow One",
        price: 5.95,
        description: "Mango & Pear",
        allergens: [],
      },
      {
        name: "The Pink One",
        price: 5.95,
        description: "Strawberry & Banana",
        allergens: [],
      },
      {
        name: "The Purple One",
        price: 5.95,
        description: "Blueberry, Banana & Blackcurrant",
        allergens: [],
      },
    ],
  },
  {
    id: 16,
    category: "Soft Drinks",
    slogan: "Bubbles, Fizz, and Pure Refreshment!",
    items: [
      { name: "Cola", price: 2.75, allergens: [] },
      { name: "Diet Cola", price: 2.75, allergens: [] },
      { name: "Rio Tropical", price: 2.75, allergens: [] },
      { name: "Pink Lemonade", price: 2.75, allergens: [] },
      { name: "Small Still Water", price: 2.5, allergens: [] },
      {
        name: "J20 Mocks - Strawberry & Orange Mojito",
        price: 4.95,
        allergens: [],
      },
      {
        name: "J20 Mocks - Blackberry & Blueberry Mojito",
        price: 4.95,
        allergens: [],
      },
      { name: "Red Bull", price: 4.95, allergens: [] },
      {
        name: "Freez - Lime and Kiwi / Strawberry Mix / Apple and Grape",
        price: 4.95,
        allergens: [],
      },
      {
        name: "Juices - Orange, Cloudy Apple, Mango, Pineapple, Carrot",
        price: 4.95,
        allergens: [],
      },
      { name: "San Pellegrino", price: 2.95, allergens: [] },
      { name: "Appletiser", price: 2.95, allergens: [] },
      {
        name: "Sparkling Lemon and Mint",
        price: 2.95,
        allergens: [],
      },
      {
        name: "Sparkling Apple and Pear",
        price: 2.95,
        allergens: [],
      },
    ],
  },
  {
    id: 17,
    category: "Milkshakes",
    slogan: "Shaken, Blended, and Totally Indulgent!",
    items: [
      {
        name: "Chocolate / Vanilla / Strawberry",
        price: 4.95,
        allergens: ["Dairy"],
      },
      { name: "Mango Lassi", price: 5.95, allergens: ["Dairy"] },
      {
        name: "Baklava Pistachio",
        price: 5.95,
        allergens: ["Gluten", "Dairy", "Nuts"],
      },
      { name: "Mocha", price: 5.95, allergens: ["Dairy"] },
    ],
  },
  {
    id: 18,
    category: "Add Ons",
    slogan: "Your Drink, Your Way – Customize the Magic!",
    items: [
      { name: "Ice It", price: 0.2, allergens: [] },
      { name: "Dirty It (Add Espresso)", price: 0.5, allergens: [] },
      { name: "Shake It (Frappe)", price: 1.0, allergens: ["Dairy"] },
      { name: "CBD", price: 1.0, allergens: [] },
      { name: "Sweeten It (Syrup)", price: 0.5, allergens: [] },
      { name: "Icecream It", price: 1.0, allergens: ["Dairy"] },
      { name: "Bubble It", price: 0.5, allergens: [] },
    ],
  },
  {
    id: 18,
    category: "Dessert Menu",
    slogan:
      "Sweet Indulgence, Perfected – Handcrafted Desserts to Savor Every Moment!",
    displayType: "menu",
    items: [
      {
        id: 1,
        name: "Tart à la Crème Brûlée with Saffron and Vanilla",
        price: 7.95,
        allergens: ["Gluten", "Dairy", "Eggs"],
      },
      {
        id: 2,
        name: "Chocolate Ganache Mousse",
        price: 6.95,
        allergens: ["Dairy", "Eggs"],
      },
      {
        id: 3,
        name: "Red Velvet Cake",
        image:
          "https://res.cloudinary.com/dhebgz7qh/image/upload/v1767529841/Red_Velvet_Cake_ks8dt8.jpg",
        price: 6.55,
        allergens: ["Gluten", "Dairy", "Eggs"],
      },
      {
        id: 4,
        name: "Tiramisu Cake",
        price: 6.55,
        allergens: ["Gluten", "Dairy", "Eggs"],
      },
      {
        id: 5,
        name: "San Sebastian Cheesecake",
        price: 6.95,
        allergens: ["Gluten", "Dairy", "Eggs"],
      },
      {
        id: 6,
        name: "Pistachio Dream Cake",
        price: 6.55,
        image:
          "https://res.cloudinary.com/dhebgz7qh/image/upload/v1767529835/Pistachio_Dream_Cake_r6ftib.webp",
        allergens: ["Gluten", "Dairy", "Eggs", "Nuts"],
      },
      {
        id: 7,
        name: "Tres Leches (Milk Cake)",
        price: 6.55,
        allergens: ["Gluten", "Dairy", "Eggs"],
      },
      {
        id: 8,
        name: "Pistachio Baklava Tart",
        price: 7.95,
        allergens: ["Gluten", "Dairy", "Eggs", "Nuts"],
      },
      {
        id: 9,
        name: "Raspberry Tart",
        image:
          "https://res.cloudinary.com/dhebgz7qh/image/upload/v1767529832/Raspberry_Tart_gjjn8v.jpg",
        price: 6.55,
        allergens: ["Gluten", "Dairy", "Eggs"],
      },
      {
        id: 10,
        name: "Rose & Raspberry Giant Macarons",
        price: 7.55,
        allergens: ["Eggs", "Nuts"],
      },
      {
        id: 11,
        name: "Mini Eclairs",
        price: 6.95,
        allergens: ["Gluten", "Dairy", "Eggs"],
      },
      {
        id: 12,
        name: "Bowl of Ice Cream (Vanilla, Chocolate, Strawberry)",
        price: 4.95,
        allergens: ["Dairy"],
      },
    ],
  },
];

export const desertMenu = [
  {
    id: 1,
    name: "Tart à la Crème Brûlée with Saffron and Vanilla",
    price: 7.95,
  },
  {
    id: 2,
    name: "Chocolate Ganache Mousse",
    price: 6.95,
  },
  {
    id: 3,
    name: "Red Velvet Cake",
    price: 6.55,
  },
  {
    id: 4,
    name: "Tiramisu Cake",
    price: 6.55,
  },
  {
    id: 5,
    name: "San Sebastian Cheesecake",
    price: 6.95,
  },
  {
    id: 6,
    name: "Pistachio Dream Cake",
    price: 6.55,
  },
  {
    id: 7,
    name: "Tres Leches (Milk Cake)",
    price: 6.55,
  },
  {
    id: 8,
    name: "Pistachio Baklava Tart",
    price: 7.95,
  },
  {
    id: 9,
    name: "Raspberry Tart",
    price: 6.55,
  },
  {
    id: 10,
    name: "Rose & Raspberry Giant Macarons",
    price: 7.55,
  },
  {
    id: 11,
    name: "Mini Eclairs",
    price: 6.95,
  },
  {
    id: 12,
    name: "Bowl of Ice Cream (Vanilla, Chocolate, Strawberry)",
    price: 4.95,
  },
];
